// 英语补充 第4批
(function(){
  const S=window.STUDY_DATA=window.STUDY_DATA||{questions:[]};
  const mk=(id,subj,kp,type,tl,diff,stem,opts,ans,ana)=>({
    id,module:"public",subject:subj,chapter:"ch-en-vocab",knowledgePoint:kp,
    type,typeLabel:tl,difficulty:diff,difficultyLabel:diff===1?"基础":diff===2?"强化":"冲刺",
    stem,options:opts,answer:ans,analysis:ana,source:"2027考纲补充",tags:[kp,"考纲补充"]
  });
  const q=[
  mk("ne141","英语","动词短语","choice","单选",2,"The meeting has been ____ because of the storm.",
    ["called off","called on","called up","called for"],"called off",
    "call off 取消。"),
  mk("ne142","英语","动词短语","choice","单选",2,"The old couple ____ the homeless dog.",
    ["took in","took up","took out","took over"],"took in",
    "take in 收留。"),
  mk("ne143","英语","动词短语","choice","单选",2,"It ____ me 2 hours to finish the work.",
    ["took","spent","cost","paid"],"took",
    "It takes sb time to do sth。"),
  mk("ne144","英语","动词短语","choice","单选",2,"I ____ 100 yuan on the book.",
    ["spent","took","cost","paid"],"spent",
    "sb spend money on sth。"),
  mk("ne145","英语","动词短语","choice","单选",2,"The book ____ me 50 yuan.",
    ["cost","spent","took","paid"],"cost",
    "sth cost sb money。"),
  mk("ne146","英语","词汇辨析","choice","单选",2,"He ____ a lot of time reading.",
    ["spends","takes","costs","pays"],"spends",
    "sb spend time (in) doing。"),
  mk("ne147","英语","词汇辨析","choice","单选",2,"Please ____ me the book.",
    ["pass","pass on","pass by","pass away"],"pass",
    "pass sb sth 把某物递给某人。"),
  mk("ne148","英语","词汇辨析","choice","单选",2,"He was ____ to see her.",
    ["surprised","surprising","surprise","surprisingly"],"surprised",
    "修饰人用 surprised。"),
  mk("ne149","英语","词汇辨析","choice","单选",2,"The story is really ____.",
    ["moving","moved","move","movement"],"moving",
    "修饰事物 story 用 moving 感人的。"),
  mk("ne150","英语","词汇辨析","choice","单选",2,"I am ____ with the result.",
    ["satisfied","satisfying","satisfy","satisfaction"],"satisfied",
    "be satisfied with 对……满意。"),
  mk("ne151","英语","固定搭配","choice","单选",2,"He is interested ____ sports.",
    ["in","at","on","with"],"in",
    "be interested in。"),
  mk("ne152","英语","固定搭配","choice","单选",2,"She is busy ____ her homework.",
    ["doing","to do","do","does"],"doing",
    "be busy doing sth。"),
  mk("ne153","英语","固定搭配","choice","单选",2,"He is good ____ playing basketball.",
    ["at","in","on","with"],"at",
    "be good at。"),
  mk("ne154","英语","固定搭配","choice","单选",2,"I am looking forward ____ you.",
    ["to seeing","to see","seeing","see"],"to seeing",
    "look forward to doing。"),
  mk("ne155","英语","时态","choice","单选",1,"The sun ____ in the east.",
    ["rises","rose","is rising","rise"],"rises",
    "客观真理一般现在时。"),
  mk("ne156","英语","时态","choice","单选",2,"I ____ my homework when the phone rang.",
    ["was doing","did","am doing","do"],"was doing",
    "when 从句过去，主句过去进行。"),
  mk("ne157","英语","时态","choice","单选",2,"She ____ here since 2020.",
    ["has lived","lived","lives","is living"],"has lived",
    "since 用现在完成时。"),
  mk("ne158","英语","语态","choice","单选",2,"The bridge ____ last year.",
    ["was built","built","is built","builds"],"was built",
    "过去时被动。"),
  mk("ne159","英语","语态","choice","单选",2,"The problem ____ at the meeting now.",
    ["is being discussed","is discussed","was discussed","discusses"],"is being discussed",
    "now 现在进行时被动。"),
  mk("ne160","英语","情态动词","choice","单选",2,"You ____ finish it today; tomorrow is OK.",
    ["needn't","must","can't","may"],"needn't",
    "由后句“明天也行”推断不必今天完成。"),
  mk("ne161","英语","情态动词","choice","单选",2,"He ____ be in the library; the light is on.",
    ["must","can","need","would"],"must",
    "肯定推测 must。"),
  mk("ne162","英语","定语从句","choice","单选",2,"This is the place ____ we visited last year.",
    ["which","where","when","who"],"which",
    "visit 是及物动词，从句缺宾语，用 which/that。"),
  mk("ne163","英语","定语从句","choice","单选",2,"The reason ____ he was late is unknown.",
    ["why","which","that","when"],"why",
    "先行词 reason，从句不缺主宾，用 why。"),
  mk("ne164","英语","状语从句","choice","单选",2,"____ hard he tried, he couldn't open the door.",
    ["However","Whatever","Whenever","Wherever"],"However",
    "however+adj/adv 无论多么。"),
  mk("ne165","英语","状语从句","choice","单选",2,"I will go ____ I am needed.",
    ["wherever","however","whatever","whoever"],"wherever",
    "wherever 无论哪里。"),
  mk("ne166","英语","非谓语","choice","单选",2,"I heard someone ____ at the door.",
    ["knocking","knock","knocked","to knock"],"knocking",
    "hear sb doing 听见正在做。"),
  mk("ne167","英语","非谓语","choice","单选",2,"The book ____ on the desk is mine.",
    ["lying","lie","lay","lain"],"lying",
    "book 与 lie 主动，用现在分词作定语。"),
  mk("ne168","英语","虚拟","choice","单选",3,"If I ____ rich, I would help the poor.",
    ["were","am","was","be"],"were",
    "与现在相反虚拟，be 用 were。"),
  mk("ne169","英语","虚拟","choice","单选",3,"It is important that he ____ there on time.",
    ["be","is","was","will be"],"be",
    "It is important that...(should) do 虚拟。"),
  mk("ne170","英语","阅读主旨","choice","阅读",2,"The passage mainly tells us ___.",
    ["how to keep healthy","how to study","how to make friends","how to travel"],"how to keep healthy",
    "主旨题。"),
  mk("ne171","英语","阅读细节","choice","阅读",2,"According to the passage, the best time to read is ___.",
    ["morning","afternoon","evening","night"],"morning",
    "细节题。"),
  mk("ne172","英语","阅读词义","choice","阅读",2,"The word \"ancient\" means ___.",
    ["very old","very new","very long","very short"],"very old",
    "ancient 古代的=very old。"),
  mk("ne173","英语","阅读推断","choice","阅读",3,"We can learn from the passage that ___.",
    ["reading is important","reading is boring","reading is useless","reading is difficult"],"reading is important",
    "推断。"),
  mk("ne174","英语","阅读填空","blank","阅读填空",2,"The library opens at ____ a.m.",
    null,"8:00",
    "细节填空。"),
  mk("ne175","英语","阅读填空","blank","阅读填空",2,"The writer's favorite sport is ____.",
    null,"basketball",
    "细节填空。"),
  mk("ne176","英语","英译汉","choice","翻译",2,"He is too young to go to school.",
    ["他太小还不能上学","他太年轻不能上学","他太小上学","他够大上学"],"他太小还不能上学",
    "too...to 太……而不能。"),
  mk("ne177","英语","英译汉","choice","翻译",2,"I have never seen such a beautiful place.",
    ["我从没见过这么美的地方","我从未看美丽地方","我看没见过美","美丽地方我没"],"我从没见过这么美的地方",
    "现在完成时+such。"),
  mk("ne178","英语","汉译英","write","写作",3,"翻译：“熟能生巧。”",
    null,"Practice makes perfect.",
    "谚语。"),
  mk("ne179","英语","应用文写作","write","写作",3,"写一封电子邮件给朋友，介绍你的大学生活（不少于80词）。",
    null,"Dear..., How is everything? Let me tell you about my college life...",
    "邮件格式：主题+称呼+正文+落款。"),
  mk("ne180","英语","应用文写作","write","写作",3,"写一则失物招领启事（不少于80词）。",
    null,"Lost: I lost my bag on the playground...",
    "格式：标题+物品特征+联系方式。")
  ];
  S.questions=S.questions.concat(q);
})();
