// 英语补充 第1批（词汇语法）
(function(){
  const S=window.STUDY_DATA=window.STUDY_DATA||{questions:[]};
  const mk=(id,subj,kp,type,tl,diff,stem,opts,ans,ana)=>({
    id,module:"public",subject:subj,chapter:"ch-en-vocab",knowledgePoint:kp,
    type,typeLabel:tl,difficulty:diff,difficultyLabel:diff===1?"基础":diff===2?"强化":"冲刺",
    stem,options:opts,answer:ans,analysis:ana,source:"2027考纲补充",tags:[kp,"考纲补充"]
  });
  const q=[
  mk("ne1","英语","词汇辨析","choice","单选",1,"The company will ____ a new branch in Guangzhou.",
    ["open","open up","open on","open out"],"open up",
    "open up 开设/开办（新业务/分支机构）。"),
  mk("ne2","英语","词汇辨析","choice","单选",1,"Please ____ your address on the form.",
    ["fill in","fill out","fill up","fill with"],"fill in",
    "fill in 填写（表格）。"),
  mk("ne3","英语","动词短语","choice","单选",1,"The meeting has been ____ until next Friday.",
    ["put off","put up","put on","put out"],"put off",
    "put off 推迟。"),
  mk("ne4","英语","动词短语","choice","单选",1,"I ____ my old friend in the street yesterday.",
    ["ran into","ran out","ran over","ran away"],"ran into",
    "run into 偶遇。"),
  mk("ne5","英语","动词短语","choice","单选",2,"Please ____ your coat; it's cold outside.",
    ["put on","put up","put out","put down"],"put on",
    "put on 穿上。"),
  mk("ne6","英语","动词短语","choice","单选",2,"The fire was ____ soon.",
    ["put out","put off","put up","put on"],"put out",
    "put out 扑灭。"),
  mk("ne7","英语","介词","choice","单选",1,"She is good ____ playing the piano.",
    ["at","in","on","for"],"at",
    "be good at 擅长。"),
  mk("ne8","英语","介词","choice","单选",1,"He has been in Beijing ____ 2020.",
    ["for","since","from","in"],"since",
    "since+时间点，用于完成时。"),
  mk("ne9","英语","介词","choice","单选",1,"We usually go to school ____ bus.",
    ["by","on","with","in"],"by",
    "by+交通工具表出行方式。"),
  mk("ne10","英语","连词","choice","单选",1,"Hurry up, ____ you'll be late.",
    ["and","but","or","so"],"or",
    "or 否则。"),
  mk("ne11","英语","连词","choice","单选",2,"____ he is young, he knows a lot.",
    ["Because","Although","If","When"],"Although",
    "although 虽然，引导让步状语从句。"),
  mk("ne12","英语","代词","choice","单选",1,"This book is ____.",
    ["my","me","mine","I"],"mine",
    "名词性物主代词 mine=my book。"),
  mk("ne13","英语","代词","choice","单选",1,"____ is important to learn English well.",
    ["This","That","It","What"],"It",
    "It 作形式主语，真正主语是后面的不定式。"),
  mk("ne14","英语","时态","choice","单选",1,"I ____ to school every day.",
    ["go","goes","going","went"],"go",
    "一般现在时，主语 I，用动词原形。"),
  mk("ne15","英语","时态","choice","单选",1,"She ____ TV now.",
    ["watches","watched","is watching","watch"],"is watching",
    "now 提示现在进行时。"),
  mk("ne16","英语","时态","choice","单选",1,"They ____ football yesterday.",
    ["play","played","are playing","will play"],"played",
    "yesterday 用一般过去时。"),
  mk("ne17","英语","时态","choice","单选",2,"We ____ each other since 2020.",
    ["know","knew","have known","will know"],"have known",
    "since+时间点用现在完成时。"),
  mk("ne18","英语","时态","choice","单选",2,"By next year, I ____ here for 3 years.",
    ["will work","will have worked","work","worked"],"will have worked",
    "by+将来时间用将来完成时。"),
  mk("ne19","英语","语态","choice","单选",2,"The bridge ____ two years ago.",
    ["built","was built","is built","builds"],"was built",
    "桥是被建的，two years ago 用过去时被动。"),
  mk("ne20","英语","语态","choice","单选",2,"English ____ in many countries.",
    ["speaks","is spoken","spoke","speaking"],"is spoken",
    "英语被说，一般现在时被动。"),
  mk("ne21","英语","定语从句","choice","单选",2,"The man ____ is talking to Mary is my teacher.",
    ["which","who","whom","whose"],"who",
    "先行词是人，从句缺主语，用 who。"),
  mk("ne22","英语","定语从句","choice","单选",2,"This is the house ____ I lived last year.",
    ["which","that","where","when"],"where",
    "先行词是地点，从句不缺主宾，用关系副词 where。"),
  mk("ne23","英语","定语从句","choice","单选",2,"I will never forget the day ____ we met.",
    ["which","that","when","where"],"when",
    "先行词是时间，用 when。"),
  mk("ne24","英语","名词性从句","choice","单选",3,"____ he will come is still unknown.",
    ["If","Whether","That","What"],"Whether",
    "主语从句引导词，表示“是否”，且在句首用 whether 不用 if。"),
  mk("ne25","英语","宾语从句","choice","单选",2,"I don't know ____ he is right.",
    ["that","if","what","which"],"if",
    "宾语从句表“是否”用 if/whether。"),
  mk("ne26","英语","非谓语","choice","单选",2,"I enjoy ____ books.",
    ["read","reading","to read","reads"],"reading",
    "enjoy 后接动名词 doing。"),
  mk("ne27","英语","非谓语","choice","单选",2,"He decided ____ abroad.",
    ["go","going","to go","went"],"to go",
    "decide 后接不定式 to do。"),
  mk("ne28","英语","非谓语","choice","单选",2,"The book is worth ____.",
    ["read","reading","to read","being read"],"reading",
    "be worth doing 主动表被动。"),
  mk("ne29","英语","非谓语","choice","单选",3,"____ from the top, the city looks beautiful.",
    ["See","Seeing","Seen","To see"],"Seen",
    "城市是“被看”，用过去分词作状语。"),
  mk("ne30","英语","虚拟语气","choice","单选",3,"If I ____ you, I would take the job.",
    ["am","was","were","be"],"were",
    "与现在事实相反的虚拟，be 动词用 were。"),
  mk("ne31","英语","情态动词","choice","单选",2,"You ____ finish the work today; it's not urgent.",
    ["must","needn't","can't","may"],"needn't",
    "由后句“不急”推断，不必今天完成。"),
  mk("ne32","英语","情态动词","choice","单选",2,"The light is on. They ____ be at home.",
    ["must","can","need","would"],"must",
    "灯亮着→肯定在家，肯定推测用 must。"),
  mk("ne33","英语","比较级","choice","单选",1,"This book is ____ than that one.",
    ["interesting","more interesting","most interesting","interestinger"],"more interesting",
    "多音节词比较级加 more。"),
  mk("ne34","英语","最高级","choice","单选",1,"She is ____ student in our class.",
    ["good","better","best","the best"],"the best",
    "最高级前加 the。"),
  mk("ne35","英语","倒装","choice","单选",3,"Never ____ such a beautiful place.",
    ["I have seen","have I seen","I saw","did I see"],"have I seen",
    "否定词 never 放句首，部分倒装，用完成时。"),
  mk("ne36","英语","词汇辨析","choice","单选",2,"The ____ of the new city is very fast.",
    ["develop","development","developing","developed"],"development",
    "定冠词 the 后用名词 development。"),
  mk("ne37","英语","词汇辨析","choice","单选",2,"He made a careful ____ of the situation.",
    ["analysis","analyze","analytical","analyst"],"analysis",
    "make an analysis 作分析，用名词。"),
  mk("ne38","英语","固定搭配","choice","单选",2,"I am looking forward ____ you soon.",
    ["to see","to seeing","see","seeing"],"to seeing",
    "look forward to 中 to 是介词，后接 doing。"),
  mk("ne39","英语","固定搭配","choice","单选",2,"He is used to ____ early.",
    ["get up","getting up","got up","gets up"],"getting up",
    "be used to doing 习惯于做某事。"),
  mk("ne40","英语","固定搭配","choice","单选",2,"The meeting ____ until midnight.",
    ["lasted","kept","spent","took"],"lasted",
    "last 持续（时间）。"),
  mk("ne41","英语","词汇辨析","choice","单选",2,"It is ____ that he will succeed.",
    ["likely","possible probably","maybe","perhaps"],"likely",
    "It is likely that... 很可能……。"),
  mk("ne42","英语","词汇辨析","choice","单选",2,"Please ____ the difference between the two words.",
    ["say","speak","tell","talk"],"tell",
    "tell the difference 区分。"),
  mk("ne43","英语","冠词","choice","单选",1,"He is ____ honest boy.",
    ["a","an","the","/"],"an",
    "honest 中 h 不发音，元音开头，用 an。"),
  mk("ne44","英语","数词","choice","单选",1,"There are ____ days in a year.",
    ["three hundreds","three hundred","three hundreds of","hundreds"],"three hundred",
    "具体数字+hundred 不加 s。"),
  mk("ne45","英语","词性转换","choice","单选",2,"She spoke ____ at the meeting.",
    ["confidence","confident","confidently","confiding"],"confidently",
    "修饰动词 spoke 用副词 confidently。")
  ];
  S.questions=S.questions.concat(q);
})();
