// 英语补充 第5批
(function(){
  const S=window.STUDY_DATA=window.STUDY_DATA||{questions:[]};
  const mk=(id,subj,kp,type,tl,diff,stem,opts,ans,ana)=>({
    id,module:"public",subject:subj,chapter:"ch-en-vocab",knowledgePoint:kp,
    type,typeLabel:tl,difficulty:diff,difficultyLabel:diff===1?"基础":diff===2?"强化":"冲刺",
    stem,options:opts,answer:ans,analysis:ana,source:"2027考纲补充",tags:[kp,"考纲补充"]
  });
  const q=[
  mk("ne181","英语","词汇辨析","choice","单选",2,"He was ____ of having done such a silly thing.",
    ["ashamed","shame","shameful","shameless"],"ashamed",
    "be ashamed of 为……感到羞愧。"),
  mk("ne182","英语","词汇辨析","choice","单选",2,"The teacher ____ us to study hard.",
    ["encouraged","encouragement","courage","courageous"],"encouraged",
    "encourage sb to do 鼓励某人做。"),
  mk("ne183","英语","词汇辨析","choice","单选",2,"He made a ____ of 5000 yuan.",
    ["contribution","contribute","contributive","contributor"],"contribution",
    "make a contribution 做贡献。"),
  mk("ne184","英语","词汇辨析","choice","单选",2,"There is no ____ that he will succeed.",
    ["doubt","question","wonder","problem"],"doubt",
    "There is no doubt that... 毫无疑问。"),
  mk("ne185","英语","词汇辨析","choice","单选",2,"I ____ agree with you.",
    ["entirely","entire","entirety","entireless"],"entirely",
    "修饰动词 agree 用副词。"),
  mk("ne186","英语","词汇辨析","choice","单选",2,"He is a ____ boy; he never tells lies.",
    ["honest","honesty","honestly","dishonest"],"honest",
    "修饰名词 boy 用形容词 honest。"),
  mk("ne187","英语","词汇辨析","choice","单选",2,"The ____ of the medicine is unknown.",
    ["effect","affect","effective","effectively"],"effect",
    "the effect of ……的效果，用名词。"),
  mk("ne188","英语","词汇辨析","choice","单选",2,"Smoking ____ health.",
    ["affects","effects","affective","effectively"],"affects",
    "affect 动词影响；effect 名词。"),
  mk("ne189","英语","词汇辨析","choice","单选",2,"He gave me a ____ smile.",
    ["friendly","friend","friendship","friendlily"],"friendly",
    "friendly 形容词修饰 smile。"),
  mk("ne190","英语","词汇辨析","choice","单选",2,"We should protect ____ environment.",
    ["the","a","an","/"],"the",
    "the environment 特指。"),
  mk("ne191","英语","时态","choice","单选",1,"He often ____ to school by bike.",
    ["goes","go","went","going"],"goes",
    "often 一般现在时，第三人称单数。"),
  mk("ne192","英语","时态","choice","单选",2,"By this time tomorrow, I ____ in Beijing.",
    ["will be","was","am","have been"],"will be",
    "将来时。"),
  mk("ne193","英语","时态","choice","单选",2,"She ____ for 3 hours.",
    ["has been reading","reads","read","is reading"],"has been reading",
    "for 3 hours 持续到现在，用现在完成进行时。"),
  mk("ne194","英语","语态","choice","单选",2,"The work ____ by the time you come back.",
    ["will have been done","will do","has done","is done"],"will have been done",
    "将来完成时被动。"),
  mk("ne195","英语","主谓一致","choice","单选",2,"Either you or he ____ wrong.",
    ["is","are","am","be"],"is",
    "either...or 就近原则，与 he 一致。"),
  mk("ne196","英语","主谓一致","choice","单选",2,"Twenty miles ____ a long way to walk.",
    ["is","are","were","be"],"is",
    "时间/距离/金钱作整体看待用单数。"),
  mk("ne197","英语","定语从句","choice","单选",2,"I still remember the day ____ I first came to this school.",
    ["when","which","that","where"],"when",
    "先行词时间，用 when。"),
  mk("ne198","英语","名词性从句","choice","单选",3,"____ we need is more time.",
    ["What","That","Which","Whether"],"What",
    "主语从句缺宾语，用 what。"),
  mk("ne199","英语","同位语从句","choice","单选",3,"I have no idea ____ he will come.",
    ["whether","what","which","which"],"whether",
    "idea 后同位语从句表“是否”用 whether。"),
  mk("ne200","英语","非谓语","choice","单选",2,"The book is said ____ into many languages.",
    ["to have been translated","to translate","translating","translate"],"to have been translated",
    "sth is said to have been done 完成被动。"),
  mk("ne201","英语","虚拟","choice","单选",3,"He talks as if he ____ everything.",
    ["knew","knows","has known","had known"],"knew",
    "as if 虚拟，与现在相反用过去时。"),
  mk("ne202","英语","虚拟","choice","单选",3,"If only I ____ more time.",
    ["had have","have","will have","having"],"had have",
    "If only 要是……就好了，用虚拟 had。"),
  mk("ne203","英语","阅读主旨","choice","阅读",2,"The best title for the passage is ___.",
    ["The Value of Time","How to Save Money","The Way to Success","Love and Friendship"],"The Value of Time",
    "主旨题。"),
  mk("ne204","英语","阅读细节","choice","阅读",2,"Why is time important according to the passage?",
    ["It never returns","It is money","It is knowledge","It is power"],"It never returns",
    "细节题。"),
  mk("ne205","英语","阅读词义","choice","阅读",2,"The word \"precious\" means ___.",
    ["valuable","cheap","useless","heavy"],"valuable",
    "precious 珍贵的=valuable。"),
  mk("ne206","英语","阅读推断","choice","阅读",3,"What does the writer advise us to do?",
    ["Make good use of time","Spend more money","Make more friends","Travel more"],"Make good use of time",
    "推断题：作者建议。"),
  mk("ne207","英语","阅读填空","blank","阅读填空",2,"The writer believes time is ____ than money.",
    null,"more important",
    "比较级填空。"),
  mk("ne208","英语","阅读填空","blank","阅读填空",2,"We should spend time on ____ things.",
    null,"meaningful",
    "细节填空。"),
  mk("ne209","英语","英译汉","choice","翻译",2,"Where there is a will, there is a way.",
    ["有志者事竟成","有意志有路","哪里有意愿哪里有路","有志气"],"有志者事竟成",
    "谚语。"),
  mk("ne210","英语","英译汉","choice","翻译",2,"Practice makes perfect.",
    ["熟能生巧","练习完美","实践制造完美","练完美"],"熟能生巧",
    "谚语。"),
  mk("ne211","英语","汉译英","write","写作",3,"翻译：“众人拾柴火焰高。”",
    null,"Many hands make light work.",
    "谚语。"),
  mk("ne212","英语","应用文写作","write","写作",3,"写一封求职信，申请公司的销售职位（不少于80词）。",
    null,"Dear Sir/Madam, I am writing to apply for...",
    "求职信：自我介绍+申请职位+能力匹配+期待回复。"),
  mk("ne213","英语","应用文写作","write","写作",3,"写一篇关于“我的大学生活”的短文（不少于80词）。",
    null,"My college life is colorful. I study...",
    "记叙文：学习+生活+朋友+感受。"),
  mk("ne214","英语","词汇辨析","choice","单选",2,"He is always ____ help others.",
    ["ready to","ready for","readily","readiness"],"ready to",
    "be ready to do 乐于做。"),
  mk("ne215","英语","词汇辨析","choice","单选",2,"I am ____ grateful to you.",
    ["deeply","deep","depth","deepen"],"deeply",
    "修饰形容词 grateful 用副词。"),
  mk("ne216","英语","词汇辨析","choice","单选",2,"He made a serious ____ in the exam.",
    ["mistake","wrong","fault","error"],"mistake",
    "make a mistake 犯错。"),
  mk("ne217","英语","词汇辨析","choice","单选",2,"Please ____ the book to the library on time.",
    ["return","return back","return back to","return to"],"return",
    "return 本身已含 back，不与 back 连用。"),
  mk("ne218","英语","词汇辨析","choice","单选",2,"I am looking forward to ____ you soon.",
    ["seeing","see","saw","seen"],"seeing",
    "look forward to doing。"),
  mk("ne219","英语","词汇辨析","choice","单选",2,"He is used to ____ up early.",
    ["getting","get","got","gets"],"getting",
    "be used to doing 习惯于。"),
  mk("ne220","英语","词汇辨析","choice","单选",2,"The old man ____ his son for money.",
    ["depends on","depends","dependent","dependence"],"depends on",
    "depend on 依靠。")
  ];
  S.questions=S.questions.concat(q);
})();
