// 英语补充 第2批（词汇语法+阅读）
(function(){
  const S=window.STUDY_DATA=window.STUDY_DATA||{questions:[]};
  const mk=(id,subj,kp,type,tl,diff,stem,opts,ans,ana)=>({
    id,module:"public",subject:subj,chapter:"ch-en-vocab",knowledgePoint:kp,
    type,typeLabel:tl,difficulty:diff,difficultyLabel:diff===1?"基础":diff===2?"强化":"冲刺",
    stem,options:opts,answer:ans,analysis:ana,source:"2027考纲补充",tags:[kp,"考纲补充"]
  });
  const q=[
  mk("ne46","英语","动词短语","choice","单选",1,"Please ____ your shoes before entering.",
    ["take off","take up","take in","take on"],"take off",
    "take off 脱下（鞋/衣）。"),
  mk("ne47","英语","动词短语","choice","单选",1,"He ____ my invitation.",
    ["turned down","turned up","turned on","turned off"],"turned down",
    "turn down 拒绝。"),
  mk("ne48","英语","动词短语","choice","单选",2,"The plane ____ at 8 a.m. yesterday.",
    ["took off","took up","took out","took over"],"took off",
    "take off 起飞。"),
  mk("ne49","英语","动词短语","choice","单选",2,"I will ____ the company while he is away.",
    ["take over","take up","take in","take out"],"take over",
    "take over 接管。"),
  mk("ne50","英语","动词短语","choice","单选",2,"She ____ a new hobby last year.",
    ["took up","took off","took out","took to"],"took up",
    "take up 开始从事（爱好）。"),
  mk("ne51","英语","固定搭配","choice","单选",1,"I am interested ____ science.",
    ["at","in","on","to"],"in",
    "be interested in 对……感兴趣。"),
  mk("ne52","英语","固定搭配","choice","单选",1,"He is good ____ math.",
    ["at","in","on","for"],"at",
    "be good at。"),
  mk("ne53","英语","固定搭配","choice","单选",2,"She is afraid ____ snakes.",
    ["of","for","with","at"],"of",
    "be afraid of 害怕。"),
  mk("ne54","英语","固定搭配","choice","单选",2,"The book is divided ____ 10 units.",
    ["into","in","to","for"],"into",
    "be divided into 被分成。"),
  mk("ne55","英语","固定搭配","choice","单选",2,"He succeeded ____ passing the exam.",
    ["in","on","at","with"],"in",
    "succeed in doing 成功做某事。"),
  mk("ne56","英语","时态","choice","单选",1,"Look! The children ____ in the park.",
    ["play","played","are playing","have played"],"are playing",
    "Look! 提示现在进行时。"),
  mk("ne57","英语","时态","choice","单选",2,"I ____ my homework when he came in.",
    ["do","did","was doing","have done"],"was doing",
    "when 从句过去时，主句用过去进行时。"),
  mk("ne58","英语","时态","choice","单选",2,"By the time he arrived, the train ____.",
    ["left","has left","had left","leaves"],"had left",
    "by the time+过去，主句用过去完成时。"),
  mk("ne59","英语","语态","choice","单选",2,"The work ____ by the team now.",
    ["is done","is being done","was done","has done"],"is being done",
    "now 提示现在进行时被动。"),
  mk("ne60","英语","主谓一致","choice","单选",2,"Neither he nor I ____ a doctor.",
    ["am","is","are","be"],"am",
    "neither...nor... 就近原则，谓语与 I 一致用 am。"),
  mk("ne61","英语","主谓一致","choice","单选",2,"The teacher with students ____ coming.",
    ["is","are","were","be"],"is",
    "主语 The teacher 单数，with 短语不影响。"),
  mk("ne62","英语","定语从句","choice","单选",2,"The book ____ cover is red is mine.",
    ["which","that","whose","where"],"whose",
    "表示“……的”所属关系用 whose。"),
  mk("ne63","英语","定语从句","choice","单选",3,"This is the best film ____ I have ever seen.",
    ["which","that","what","it"],"that",
    "先行词被最高级修饰，用 that 不用 which。"),
  mk("ne64","英语","状语从句","choice","单选",2,"I will call you ____ I arrive.",
    ["as soon as","as long as","as well as","as far as"],"as soon as",
    "as soon as 一……就……。"),
  mk("ne65","英语","状语从句","choice","单选",2,"____ it rains, we will stay at home.",
    ["If","Unless","Though","Because"],"If",
    "if 引导条件状语从句。"),
  mk("ne66","英语","状语从句","choice","单选",2,"He ran fast ____ he could catch the bus.",
    ["so that","such that","in order to","as that"],"so that",
    "so that 引导目的状语从句。"),
  mk("ne67","英语","非谓语","choice","单选",2,"I have a lot of work ____ today.",
    ["do","to do","doing","done"],"to do",
    "不定式作后置定语。"),
  mk("ne68","英语","非谓语","choice","单选",2,"The teacher made us ____ the classroom.",
    ["clean","to clean","cleaning","cleaned"],"clean",
    "make sb do sth 省 to 不定式。"),
  mk("ne69","英语","非谓语","choice","单选",3,"I saw him ____ the room.",
    ["enter","to enter","entering","entered"],"enter",
    "see sb do sth 看见全过程。"),
  mk("ne70","英语","虚拟","choice","单选",3,"I wish I ____ fly.",
    ["can","could","may","might"],"could",
    "wish 后虚拟，用过去式 could。"),
  mk("ne71","英语","词汇辨析","choice","单选",2,"He is ____ for the meeting.",
    ["responsible","response","responsibility","responsible to"],"responsible",
    "be responsible for 对……负责。"),
  mk("ne72","英语","词汇辨析","choice","单选",2,"The price is too ____ for me.",
    ["high","expensive","dear","cheap"],"high",
    "price 用 high/low；物品用 expensive/cheap。"),
  mk("ne73","英语","词汇辨析","choice","单选",2,"I ____ a mistake.",
    ["did","made","took","had"],"made",
    "make a mistake 犯错。"),
  mk("ne74","英语","词汇辨析","choice","单选",2,"Please ____ attention to your spelling.",
    ["pay","take","give","make"],"pay",
    "pay attention to 注意。"),
  mk("ne75","英语","词汇辨析","choice","单选",2,"He ____ a good idea at the meeting.",
    ["came up with","came on","came out","came across"],"came up with",
    "come up with 想出（主意）。"),
  mk("ne76","英语","词汇辨析","choice","单选",2,"The problem is easy to ____.",
    ["solve","answer","reply","deal"],"solve",
    "solve the problem 解决问题。"),
  mk("ne77","英语","词汇辨析","choice","单选",2,"She ____ a good education.",
    ["received","accepted","got","took"],"received",
    "receive education 接受教育。"),
  mk("ne78","英语","词汇辨析","choice","单选",2,"I am ____ tired today.",
    ["a bit","a bit of","bit","bits"],"a bit",
    "a bit 修饰形容词；a bit of 修饰名词。"),
  mk("ne79","英语","词汇辨析","choice","单选",2,"There is ____ water in the bottle.",
    ["a little","little","a few","few"],"a little",
    "water 不可数，肯定用 a little。"),
  mk("ne80","英语","词汇辨析","choice","单选",2,"He has ____ friends, so he often feels lonely.",
    ["few","a few","little","a little"],"few",
    "friends 可数，否定“几乎没有”用 few。"),
  mk("ne81","英语","阅读主旨","choice","阅读",2,"What is the main idea of the passage?",
    ["The importance of reading","How to make friends","The weather","The history"],"The importance of reading",
    "主旨题：找首段和各段首句。"),
  mk("ne82","英语","阅读细节","choice","阅读",2,"According to the passage, why did the author go to Beijing?",
    ["For business","For travel","For study","For a meeting"],"For study",
    "细节题：回原文定位关键词。"),
  mk("ne83","英语","阅读词义","choice","阅读",2,"The word \"benefit\" in line 5 probably means ___.",
    ["advantage","interest","money","profit"],"advantage",
    "词义题：根据上下文猜。benefit=好处/优势。"),
  mk("ne84","英语","阅读推断","choice","阅读",3,"What can we infer from the passage?",
    ["The author likes the city","The author dislikes the city","The author is neutral","The author is uncertain"],"The author likes the city",
    "推断题：依据作者用词感情色彩。"),
  mk("ne85","英语","阅读细节","choice","阅读",2,"How many people attended the meeting?",
    ["About 20","About 30","About 40","About 50"],"About 30",
    "细节题：数字题回原文定位。"),
  mk("ne86","英语","阅读填空","blank","阅读填空",2,"The meeting will be held in ____.",
    null,"Room 301",
    "阅读填空：根据原文填空，不超过4个词。"),
  mk("ne87","英语","阅读填空","blank","阅读填空",2,"The speaker is from ____.",
    null,"Beijing",
    "细节填空。"),
  mk("ne88","英语","英译汉","choice","翻译",2,"It is important to learn English well.",
    ["学好英语很重要","很重要学英语","学英语好重要","英语学好很"],"学好英语很重要",
    "形式主语 It 译时把真正主语提前。"),
  mk("ne89","英语","英译汉","choice","翻译",2,"The book is worth reading.",
    ["这本书值得读","这本书值读","书值得读","这书读值得"],"这本书值得读",
    "be worth doing 值得做。"),
  mk("ne90","英语","汉译英","write","写作",3,"请把“他每天早上6点起床”翻译成英文。",
    null,"He gets up at 6 every morning.",
    "一般现在时，第三人称单数。")
  ];
  S.questions=S.questions.concat(q);
})();
