// 英语补充 第3批
(function(){
  const S=window.STUDY_DATA=window.STUDY_DATA||{questions:[]};
  const mk=(id,subj,kp,type,tl,diff,stem,opts,ans,ana)=>({
    id,module:"public",subject:subj,chapter:"ch-en-vocab",knowledgePoint:kp,
    type,typeLabel:tl,difficulty:diff,difficultyLabel:diff===1?"基础":diff===2?"强化":"冲刺",
    stem,options:opts,answer:ans,analysis:ana,source:"2027考纲补充",tags:[kp,"考纲补充"]
  });
  const q=[
  mk("ne91","英语","动词短语","choice","单选",2,"The old building was ____ last year.",
    ["pulled down","pulled up","pulled out","pulled over"],"pulled down",
    "pull down 拆除。"),
  mk("ne92","英语","动词短语","choice","单选",2,"Please ____ the form first.",
    ["fill out","fill in","fill up","fill with"],"fill out",
    "fill out 填写（完整表格）。"),
  mk("ne93","英语","动词短语","choice","单选",2,"She has ____ a lot of progress.",
    ["made","done","had","taken"],"made",
    "make progress 取得进步。"),
  mk("ne94","英语","动词短语","choice","单选",2,"I will ____ the matter right away.",
    ["look into","look up","look for","look after"],"look into",
    "look into 调查。"),
  mk("ne95","英语","动词短语","choice","单选",2,"My sister ____ my children when I am away.",
    ["looks after","looks for","looks up","looks out"],"looks after",
    "look after 照顾。"),
  mk("ne96","英语","动词短语","choice","单选",2,"____ your coat; it's warm inside.",
    ["Take off","Put on","Take up","Put up"],"Take off",
    "由后句“里面暖和”推断脱外套。"),
  mk("ne97","英语","固定搭配","choice","单选",1,"He arrived ____ Beijing yesterday.",
    ["in","at","to","/"],"in",
    "arrive in+大地方；arrive at+小地方。"),
  mk("ne98","英语","固定搭配","choice","单选",1,"She is good ____ singing.",
    ["at","in","on","with"],"at",
    "be good at。"),
  mk("ne99","英语","固定搭配","choice","单选",2,"I am proud ____ my students.",
    ["of","for","with","at"],"of",
    "be proud of 为……自豪。"),
  mk("ne100","英语","固定搭配","choice","单选",2,"He is fond ____ music.",
    ["of","for","with","at"],"of",
    "be fond of 喜欢。"),
  mk("ne101","英语","时态","choice","单选",2,"By the end of last year, I ____ 1000 English words.",
    ["have learned","had learned","learned","learn"],"had learned",
    "by+过去时间用过去完成时。"),
  mk("ne102","英语","时态","choice","单选",2,"Look at the clouds. It ____ soon.",
    ["rains","is going to rain","rained","rain"],"is going to rain",
    "有迹象表明即将发生，用 be going to。"),
  mk("ne103","英语","语态","choice","单选",2,"The work must ____ today.",
    ["finish","be finished","finished","finishing"],"be finished",
    "情态动词被动：must be done。"),
  mk("ne104","英语","情态动词","choice","单选",2,"You ____ not smoke here; it's a hospital.",
    ["must","need","may","can"],"must",
    "mustn't 禁止。"),
  mk("ne105","英语","情态动词","choice","单选",2,"He ____ be at home, because the door is locked.",
    ["must","mustn't","can","may"],"mustn't",
    "门锁了→肯定不在家，否定推测 can't/mustn't。"),
  mk("ne106","英语","定语从句","choice","单选",2,"The man ____ you met yesterday is my boss.",
    ["who","whom","which","whose"],"whom",
    "先行词人，从句作宾语，用 whom。"),
  mk("ne107","英语","同位语从句","choice","单选",3,"The news ____ he won the prize is true.",
    ["which","that","what","why"],"that",
    "news 后同位语从句，that 不充当成分。"),
  mk("ne108","英语","强调句","choice","单选",3,"It was in the park ____ I met her.",
    ["where","that","which","when"],"that",
    "强调句 It is/was...that...。"),
  mk("ne109","英语","倒装","choice","单选",3,"Only in this way ____ solve the problem.",
    ["you can","can you","you will","do you"],"can you",
    "only+状语放句首，部分倒装。"),
  mk("ne110","英语","虚拟","choice","单选",3,"If I had known, I ____ you.",
    ["would tell","would have told","told","had told"],"would have told",
    "与过去事实相反：had done + would have done。"),
  mk("ne111","英语","词汇辨析","choice","单选",2,"The ____ of the earth is round.",
    ["form","shape","figure","size"],"shape",
    "shape 形状。"),
  mk("ne112","英语","词汇辨析","choice","单选",2,"He was ____ in a car accident.",
    ["hurt","injured","wounded","harmed"],"injured",
    "事故中受伤用 injured。"),
  mk("ne113","英语","词汇辨析","choice","单选",2,"Please ____ the book on the desk.",
    ["lay","lie","laid","lain"],"lay",
    "lay 放置（及物）；lie 躺/位于。"),
  mk("ne114","英语","词汇辨析","choice","单选",2,"The river ____ 200 kilometers long.",
    ["is","are","has","have"],"is",
    "河流长度作整体看待，用单数。"),
  mk("ne115","英语","词汇辨析","choice","单选",2,"I am ____ sorry for being late.",
    ["terrible","terribly","terror","terrorize"],"terribly",
    "修饰形容词 sorry 用副词。"),
  mk("ne116","英语","阅读主旨","choice","阅读",2,"What is the best title for the passage?",
    ["How to Learn English Well","English Grammar","English Words","English Culture"],"How to Learn English Well",
    "主旨题：选概括全文的选项。"),
  mk("ne117","英语","阅读细节","choice","阅读",2,"Why did the author change his job?",
    ["For better pay","For more challenge","For health reason","For family"],"For more challenge",
    "细节题：定位原文原因句。"),
  mk("ne118","英语","阅读细节","choice","阅读",2,"When did the company set up its branch in Shanghai?",
    ["In 2020","In 2021","In 2022","In 2023"],"In 2021",
    "细节：数字题。"),
  mk("ne119","英语","阅读词义","choice","阅读",2,"The word \"crucial\" in line 3 means ___.",
    ["important","easy","difficult","interesting"],"important",
    "crucial=至关重要的。"),
  mk("ne120","英语","阅读推断","choice","阅读",3,"What is the author's attitude towards the project?",
    ["Supportive","Critical","Neutral","Doubtful"],"Supportive",
    "推断：看作者用词（success/great/worthwhile）。"),
  mk("ne121","英语","阅读填空","blank","阅读填空",2,"The course lasts ____ weeks.",
    null,"8",
    "细节填空。"),
  mk("ne122","英语","阅读填空","blank","阅读填空",2,"The deadline for application is ____.",
    null,"May 1st",
    "细节填空。"),
  mk("ne123","英语","英译汉","choice","翻译",2,"Not only did he study hard, but he also helped others.",
    ["他不仅努力学习，还帮助别人","他学习努力还帮人","不仅他学习努力","他学习好"],"他不仅努力学习，还帮助别人",
    "not only...but also 不仅……而且。"),
  mk("ne124","英语","英译汉","choice","翻译",2,"The more you read, the more you know.",
    ["你读得越多，知道得越多","读越多越知道","你读知道多","读多知道多"],"你读得越多，知道得越多",
    "the more...the more 越……越……。"),
  mk("ne125","英语","汉译英","write","写作",3,"请翻译：“学习是一个永无止境的过程。”",
    null,"Learning is a never-ending process.",
    "动名词作主语。"),
  mk("ne126","英语","应用文写作","write","写作",3,"写一封邀请信，邀请朋友参加你的生日聚会（不少于80词）。",
    null,"Dear..., I would like to invite you to...",
    "格式：称呼+正文+落款；时间地点内容齐全。"),
  mk("ne127","英语","应用文写作","write","写作",3,"写一封感谢信，感谢老师的帮助（不少于80词）。",
    null,"Dear teacher, I am writing to thank you for...",
    "格式：感谢信，表达感谢+具体帮助+再次感谢。"),
  mk("ne128","英语","应用文写作","write","写作",3,"写一张请假条，因为生病不能上课（不少于80词）。",
    null,"Dear teacher, I am writing to ask for leave...",
    "请假条：原因+时间+请求批准。"),
  mk("ne129","英语","词汇辨析","choice","单选",2,"He is ____ of speaking in public.",
    ["afraid","fear","fright","terror"],"afraid",
    "be afraid of 害怕。"),
  mk("ne130","英语","词汇辨析","choice","单选",2,"Please ____ the difference between \"affect\" and \"effect\".",
    ["say","speak","tell","talk"],"tell",
    "tell the difference 区分。"),
  mk("ne131","英语","词汇辨析","choice","单选",2,"I ____ my keys everywhere but couldn't find them.",
    ["looked for","found","looked up","looked after"],"looked for",
    "look for 寻找（过程）；find 找到（结果）。"),
  mk("ne132","英语","词汇辨析","choice","单选",2,"He ____ to me for being late.",
    ["apologized","thanked","explained","spoke"],"apologized",
    "apologize to sb for sth 因某事向某人道歉。"),
  mk("ne133","英语","词汇辨析","choice","单选",2,"The film is ____. I want to see it again.",
    ["excited","exciting","excite","excitement"],"exciting",
    "修饰事物用 exciting；修饰人用 excited。"),
  mk("ne134","英语","词汇辨析","choice","单选",2,"I am ____ in this book.",
    ["interest","interesting","interested","interests"],"interested",
    "be interested in 对……感兴趣。"),
  mk("ne135","英语","词汇辨析","choice","单选",2,"The news is ____.",
    ["surprising","surprised","surprise","surprisingly"],"surprising",
    "修饰事物 news 用 surprising。"),
  mk("ne136","英语","时态","choice","单选",1,"Water ____ at 100°C.",
    ["boil","boils","boiled","is boiling"],"boils",
    "客观真理用一般现在时。"),
  mk("ne137","英语","冠词","choice","单选",1,"____ sun rises in the east.",
    ["A","An","The","/"],"The",
    "世界上独一无二的事物前加 the。"),
  mk("ne138","英语","介词","choice","单选",2,"He will come back ____ a week.",
    ["after","in","for","since"],"in",
    "in+时间段表“……之后”，用于将来时。"),
  mk("ne139","英语","介词","choice","单选",2,"He has lived here ____ 10 years.",
    ["after","in","for","since"],"for",
    "for+时间段。"),
  mk("ne140","英语","代词","choice","单选",2,"There is ____ water left. We need to buy some.",
    ["few","a few","little","a little"],"little",
    "water 不可数，否定“几乎没有”用 little。")
  ];
  S.questions=S.questions.concat(q);
})();
