/* 学习一刻 · 分科知识点 */
window.STUDY_DATA = window.STUDY_DATA || {};
window.STUDY_DATA.LEARN_BOOK = {
  高等数学: [
    {
      chapter: "极限与连续",
      points: [
        {
          id: "L-lim-1",
          name: "函数定义域",
          level: "基础",
          minutes: 5,
          define: "使函数有意义的 x 的集合。",
          why: "考纲要求会求定义域；选择题高频。",
          core: [
            { k: "分式", v: "分母 ≠ 0" },
            { k: "偶次根号", v: "被开方数 ≥ 0" },
            { k: "对数", v: "真数 > 0" },
            { k: "实际问题", v: "按题意限非负/整数" },
          ],
          steps: ["列出所有限制条件", "解不等式组", "写成区间或集合"],
          example: {
            stem: "求 f(x)=frac{1}{x−2}+√x 的定义域。",
            analysis: "x−2≠0 ⇒ x≠2；√x ⇒ x≥0。定义域 [0,2)∪(2,+∞)。",
          },
          mistakes: ["只写一半条件", "漏掉开闭区间括号"],
          kp: "极限与连续",
        },
        {
          id: "L-lim-2",
          name: "极限的定义",
          level: "基础",
          minutes: 6,
          define: "当 x 无限接近某值时，函数值无限接近的常数。",
          why: "后续所有极限计算的根基；概念题必考。",
          core: [
            { k: "记号", v: "lim(x→a) f(x) = A" },
            { k: "含义", v: "x→a 时 f(x)→A" },
          ],
          steps: ["看 x 的趋向", "看 f(x) 的趋势", "若存在唯一常数即为极限"],
          example: {
            stem: "lim(x→2) (x+1) =？",
            analysis: "直接代入：2+1=3。多项式在定义点连续，可代入。",
          },
          mistakes: ["把 x→a 与 x=a 混为一谈", "忽略左右是否一致"],
          kp: "极限与连续",
        },
        {
          id: "L-lim-3",
          name: "左极限与右极限",
          level: "基础",
          minutes: 6,
          define: "左极限 x→a⁻，右极限 x→a⁺；左右相等才存在。",
          why: "分段函数、绝对值题必用。",
          core: [
            { k: "存在条件", v: "lim⁻ = lim⁺" },
            { k: "不等", v: "极限不存在" },
          ],
          steps: ["分别算左右", "比较是否相等", "下结论"],
          example: {
            stem: "f(x)=|x|/x 在 x→0 时极限？",
            analysis: "x→0⁺ 得 1，x→0⁻ 得 −1，不相等，极限不存在。",
          },
          mistakes: ["只算一边", "写成 0"],
          kp: "极限与连续",
        },
        {
          id: "L-lim-4",
          name: "无穷小与无穷大",
          level: "基础",
          minutes: 5,
          define: "极限为 0 的量是无穷小；绝对值无限增大是无穷大。",
          why: "判型与等价替换的前提。",
          core: [
            { k: "无穷小", v: "lim = 0" },
            { k: "关系", v: "无穷小的倒数是无穷大（非0）" },
          ],
          steps: ["先算极限", "判断趋向 0 还是 ∞"],
          example: {
            stem: "x→0 时，x² 是无穷小吗？",
            analysis: "是，因为 lim x²=0。",
          },
          mistakes: ["把很小的常数当无穷小"],
          kp: "极限与连续",
        },
        {
          id: "L-lim-5",
          name: "极限四则运算",
          level: "强化",
          minutes: 7,
          define: "和差积商的极限等于极限的和差积商（分母极限非 0）。",
          why: "拆分复杂极限的基础工具。",
          core: [
            { k: "条件", v: "各分极限存在" },
            { k: "商", v: "分母极限 ≠ 0" },
          ],
          steps: ["拆成简单极限", "分别求", "再合并"],
          example: {
            stem: "lim(x→1)(2x+3) =？",
            analysis: "=2·1+3=5。",
          },
          mistakes: ["分母为 0 仍除", "拆成不存在的项"],
          kp: "极限与连续",
        },
        {
          id: "L-lim-6",
          name: "等价无穷小",
          level: "强化",
          minutes: 8,
          define: "x→0 时，sinx~x，1−cosx~frac{x²}{2}，eˣ−1~x，tanx~x。",
          why: "0/0 计算题最常用捷径。",
          core: [
            { k: "只能用在", v: "乘除因子" },
            { k: "加减中", v: "先通分或泰勒" },
          ],
          steps: ["判 0/0", "找可替换因子", "替换后约分"],
          example: {
            stem: "lim(x→0) sin5x/x",
            analysis: "sin5x~5x，结果 5。",
          },
          mistakes: ["加减中乱换", "1−cosx 当成 x"],
          kp: "极限与连续",
        },
        {
          id: "L-lim-7",
          name: "两个重要极限",
          level: "强化",
          minutes: 8,
          define: "lim sinx/x=1；lim(1+1/x)^x=e。",
          why: "选择填空必背。",
          core: [
            { k: "三角型", v: "lim(x→0) sin(ax)/x = a" },
            { k: "e 型", v: "(1+a/x)^x → e^a" },
          ],
          steps: ["匹配结构", "凑成标准形式", "写出结果"],
          example: {
            stem: "lim(x→∞)(1+2/x)^x",
            analysis: "=e²。",
          },
          mistakes: ["指数上的 2 没进 e"],
          kp: "极限与连续",
        },
        {
          id: "L-lim-8",
          name: "洛必达法则",
          level: "强化",
          minutes: 8,
          define: "0/0 或 ∞/∞ 时，极限等于分子分母导数之比的极限。",
          why: "计算大题备用法。",
          core: [
            { k: "前提", v: "先判型" },
            { k: "使用", v: "对分子分母分别求导" },
          ],
          steps: ["代入判型", "求导", "再算极限"],
          example: {
            stem: "lim(x→0) (eˣ−1)/x",
            analysis: "0/0 → eˣ/1 → 1。",
          },
          mistakes: ["分子分母整体求导", "非 0/0 乱用"],
          kp: "极限与连续",
        },
        {
          id: "L-lim-9",
          name: "夹逼定理",
          level: "冲刺",
          minutes: 8,
          define: "两函数极限都是 A 且夹在中间，则中间函数极限也是 A。",
          why: "n 项和、绝对值型极限。",
          core: [
            { k: "放缩", v: "找到可算极限的上下界" },
            { k: "结论", v: "上下极限相等" },
          ],
          steps: ["放缩", "求上下极限", "写出答案"],
          example: {
            stem: "lim(n→∞) (1/n²+…+n²/n²)? 简化例：|sinx|/x 夹逼",
            analysis: "典型题用 −1≤sinx≤1 放缩。",
          },
          mistakes: ["放缩方向错误"],
          kp: "极限与连续",
        },
        {
          id: "L-lim-10",
          name: "极限存在判断",
          level: "冲刺",
          minutes: 7,
          define: "左右极限相等 ⇔ 极限存在（有限）。",
          why: "概念选择题。",
          core: [{ k: "等价说法", v: "lim⁻ = lim⁺ = 有限值" }],
          steps: ["算左右", "比大小"],
          example: {
            stem: "x→0 时 1/x 极限存在吗？",
            analysis: "左右为 ±∞，不相等，不存在（无穷）。",
          },
          mistakes: ["把 ∞ 当存在"],
          kp: "极限与连续",
        },
        {
          id: "L-lim-11",
          name: "连续性",
          level: "冲刺",
          minutes: 7,
          define: "lim f(x)=f(a) 则 f 在 a 连续。",
          why: "间断点题、分段函数题。",
          core: [
            { k: "三条件", v: "有定义、极限存在、相等" },
            { k: "初等函数", v: "定义区间内连续" },
          ],
          steps: ["查定义", "算极限", "比是否相等"],
          example: {
            stem: "f=frac{x²−4}{x−2} 在 x=2 连续吗？",
            analysis: "无定义，不连续；补 f(2)=4 后连续。",
          },
          mistakes: ["忽略无定义点"],
          kp: "极限与连续",
        },
        {
          id: "L-lim-12",
          name: "间断点分类",
          level: "冲刺",
          minutes: 8,
          define: "可去：极限存在；跳跃：左右不等；无穷：趋于 ∞。",
          why: "填空/选择常考分类。",
          core: [
            { k: "可去", v: "lim 存在" },
            { k: "跳跃", v: "左右极限都有限但不等" },
            { k: "无穷", v: "lim=∞" },
          ],
          steps: ["找无定义/突变点", "算左右极限", "归类"],
          example: {
            stem: "f(x)=1/x 在 x=0？",
            analysis: "无穷间断点。",
          },
          mistakes: ["可去与跳跃混"],
          kp: "极限与连续",
        },
      ],
    },
    {
      chapter: "导数与微分",
      points: [
        {
          id: "L-der-1",
          name: "导数的定义",
          level: "基础",
          minutes: 7,
          define: "f′(x)=lim(h→0)[f(x+h)−f(x)]/h。",
          why: "概念题与分段函数求导。",
          core: [{ k: "几何", v: "切线斜率" }],
          steps: ["写出增量比", "取极限"],
          example: {
            stem: "f(x)=x² 在 x=1 的导数？",
            analysis: "用定义或公式 2x，得 2。",
          },
          mistakes: ["漏极限"],
          kp: "导数与微分",
        },
        {
          id: "L-der-2",
          name: "基本求导公式",
          level: "基础",
          minutes: 8,
          define: "幂、指数、对数、三角的求导公式表。",
          why: "所有求导题的出发点。",
          core: [
            { k: "幂", v: "(xⁿ)′=nxⁿ⁻¹" },
            { k: "指数", v: "(eˣ)′=eˣ" },
            { k: "对数", v: "(lnx)′=frac{1}{x}" },
            { k: "三角", v: "(sinx)′=cosx，(cosx)′=−sinx" },
          ],
          steps: ["识别函数类型", "代公式"],
          example: {
            stem: "y=x³+lnx，求 y′。",
            analysis: "3x²+frac{1}{x}。",
          },
          mistakes: ["cosx 求导丢负号"],
          kp: "导数与微分",
        },
        {
          id: "L-der-3",
          name: "乘积与商法则",
          level: "强化",
          minutes: 8,
          define: "(uv)′=u′v+uv′；(u/v)′=frac{u′v−uv′}{v²}。",
          why: "综合求导题必用。",
          core: [{ k: "口诀", v: "前导后不导 + 后导前不导" }],
          steps: ["分清 u、v", "分别求导", "代入合并"],
          example: {
            stem: "y=x eˣ，求 y′。",
            analysis: "eˣ+x eˣ=eˣ(1+x)。",
          },
          mistakes: ["写成 u′v′"],
          kp: "导数与微分",
        },
        {
          id: "L-der-4",
          name: "复合函数（链式）",
          level: "强化",
          minutes: 8,
          define: "[f(g(x))]′=f′(g)·g′。",
          why: "sin(2x)、e^{3x}、(x²+1)ⁿ 等。",
          core: [{ k: "口诀", v: "外层导 × 内层导" }],
          steps: ["找内层 g", "外层求导", "乘 g′"],
          example: {
            stem: "y=sin(2x)，求 y′。",
            analysis: "cos(2x)·2=2cos2x。",
          },
          mistakes: ["漏内层系数"],
          kp: "导数与微分",
        },
        {
          id: "L-der-5",
          name: "微分",
          level: "强化",
          minutes: 6,
          define: "dy=f′(x)dx。",
          why: "填空常考。",
          core: [{ k: "公式", v: "dy=y′dx" }],
          steps: ["先求 y′", "乘上 dx"],
          example: {
            stem: "y=x²，求 dy|_{x=1}。",
            analysis: "y′=2x，dy=2dx。",
          },
          mistakes: ["漏 dx"],
          kp: "导数与微分",
        },
      ],
    },
    {
      chapter: "不定积分",
      points: [
        {
          id: "L-int-1",
          name: "原函数与不定积分",
          level: "基础",
          minutes: 6,
          define: "F′(x)=f(x)，则 ∫f dx=F+C。",
          why: "积分概念题。",
          core: [{ k: "关键", v: "结果必须 +C" }],
          steps: ["找一个原函数", "写 +C"],
          example: {
            stem: "∫2x dx=？",
            analysis: "x²+C。",
          },
          mistakes: ["漏 C"],
          kp: "不定积分",
        },
        {
          id: "L-int-2",
          name: "凑微分",
          level: "强化",
          minutes: 8,
          define: "∫f(g)g′dx=∫f(u)du。",
          why: "计算大题主力。",
          core: [{ k: "关键", v: "看到 g 与 g′ 同时出现" }],
          steps: ["设 u=g(x)", "换 du", "积分回代"],
          example: {
            stem: "∫2x e^{x²}dx",
            analysis: "u=x²，得 e^{x²}+C。",
          },
          mistakes: ["漏 du 系数"],
          kp: "不定积分",
        },
        {
          id: "L-int-3",
          name: "分部积分",
          level: "强化",
          minutes: 8,
          define: "∫udv=uv−∫vdu。",
          why: "多项式×指数/三角、含 ln。",
          core: [{ k: "选 u", v: "反对幂指三" }],
          steps: ["选 u、dv", "求 du、v", "代入"],
          example: {
            stem: "∫x eˣdx",
            analysis: "x eˣ−eˣ+C=eˣ(x−1)+C。",
          },
          mistakes: ["uv 符号错"],
          kp: "不定积分",
        },
      ],
    },
    {
      chapter: "定积分",
      points: [
        {
          id: "L-def-1",
          name: "牛顿-莱布尼茨公式",
          level: "强化",
          minutes: 7,
          define: "∫ₐᵇf=F(b)−F(a)。",
          why: "定积分计算核心。",
          core: [{ k: "步骤", v: "先求 F，再代限相减" }],
          steps: ["求原函数", "代上限减下限"],
          example: {
            stem: "∫₀²x²dx",
            analysis: "frac{8}{3}。",
          },
          mistakes: ["忘减 F(a)"],
          kp: "定积分",
        },
        {
          id: "L-def-2",
          name: "变限积分求导",
          level: "强化",
          minutes: 7,
          define: "d/dx∫ₐˣf(t)dt=f(x)。",
          why: "选择填空高频。",
          core: [{ k: "口诀", v: "把 t 换成 x" }],
          steps: ["写清上下限", "代入被积函数"],
          example: {
            stem: "F=∫₀ˣsin t dt，求 F′。",
            analysis: "sin x。",
          },
          mistakes: ["被积含 x 未处理"],
          kp: "定积分",
        },
      ],
    },
    {
      chapter: "微分方程",
      points: [
        {
          id: "L-ode-1",
          name: "可分离变量",
          level: "强化",
          minutes: 8,
          define: "dy/dx=g(x)h(y) 可分开积分。",
          why: "计算题常见。",
          core: [{ k: "做法", v: "dy/h(y)=g(x)dx 两边积分" }],
          steps: ["分离", "积分", "写通解含 C"],
          example: {
            stem: "y′=2xy",
            analysis: "y=Ce^{x²}。",
          },
          mistakes: ["漏 C"],
          kp: "微分方程",
        },
        {
          id: "L-ode-2",
          name: "二阶常系数齐次",
          level: "冲刺",
          minutes: 9,
          define: "y″+py′+qy=0 用特征方程 r²+pr+q=0。",
          why: "冲刺大题。",
          core: [
            { k: "两实根", v: "y=C₁e^{r₁x}+C₂e^{r₂x}" },
            { k: "重根", v: "y=(C₁+C₂x)e^{rx}" },
            { k: "复根", v: "e^{αx}(C₁cosβx+C₂sinβx)" },
          ],
          steps: ["写特征方程", "解根", "套通解"],
          example: {
            stem: "y″−y′−6y=0",
            analysis: "r=3,−2，y=C₁e^{3x}+C₂e^{−2x}。",
          },
          mistakes: ["特征根算错"],
          kp: "微分方程",
        },
      ],
    },
  ],

  英语: [
    {
      chapter: "时态与语态",
      points: [
        {
          id: "E-ten-1",
          name: "一般现在时",
          level: "基础",
          minutes: 5,
          define: "表示经常、习惯或客观事实。",
          why: "最基础时态，作文也常用。",
          core: [
            { k: "形式", v: "do / does" },
            { k: "标志词", v: "every day, usually, often" },
          ],
          steps: ["看时间状语", "主语三单加 s"],
          example: {
            stem: "He ____ (go) to school every day.",
            analysis: "goes。every day 用一般现在；主语 He 三单。",
          },
          mistakes: ["三单不加 s"],
          kp: "时态与语态",
        },
        {
          id: "E-ten-2",
          name: "一般过去时",
          level: "基础",
          minutes: 5,
          define: "过去某个时间发生的动作。",
          why: "叙事阅读与作文。",
          core: [
            { k: "形式", v: "did / was-were" },
            { k: "标志", v: "yesterday, last week, ago" },
          ],
          steps: ["找过去时间", "动词用过去式"],
          example: {
            stem: "I ____ (see) him yesterday.",
            analysis: "saw。",
          },
          mistakes: ["用现在时"],
          kp: "时态与语态",
        },
        {
          id: "E-ten-3",
          name: "现在进行时",
          level: "基础",
          minutes: 5,
          define: "此刻正在发生的动作。",
          why: "听力阅读高频。",
          core: [{ k: "形式", v: "am/is/are + doing" }],
          steps: ["找 now/look/listen", "be + 动词 ing"],
          example: {
            stem: "Look! The children ____ (play).",
            analysis: "are playing。",
          },
          mistakes: ["漏 be"],
          kp: "时态与语态",
        },
        {
          id: "E-ten-4",
          name: "现在完成时",
          level: "强化",
          minutes: 7,
          define: "过去发生对现在有影响，或从过去持续到现在。",
          why: "考试最爱考的时态。",
          core: [
            { k: "形式", v: "have/has + done" },
            { k: "标志", v: "for, since, already, yet" },
          ],
          steps: ["认标志词", "选 have/has", "动词过去分词"],
          example: {
            stem: "He ____ (live) here for 3 years.",
            analysis: "has lived。for + 完成时。",
          },
          mistakes: ["for/since 用过去时"],
          kp: "时态与语态",
        },
        {
          id: "E-ten-5",
          name: "过去完成时",
          level: "强化",
          minutes: 7,
          define: "过去某一时间之前已完成的动作（过去的过去）。",
          why: "记叙文与从句中常见。",
          core: [{ k: "形式", v: "had + done" }],
          steps: ["找两个过去时间", "更早的用 had done"],
          example: {
            stem: "When I arrived, the meeting ____ (begin).",
            analysis: "had begun。",
          },
          mistakes: ["两个都用一般过去"],
          kp: "时态与语态",
        },
        {
          id: "E-ten-6",
          name: "被动语态",
          level: "强化",
          minutes: 7,
          define: "主语是动作承受者：be + 过去分词。",
          why: "科技说明文高频。",
          core: [{ k: "结构", v: "be + done (+by…)" }],
          steps: ["判断主被动", "按时态变 be", "加过去分词"],
          example: {
            stem: "The bridge ____ (build) next year.",
            analysis: "will be built。",
          },
          mistakes: ["漏 be"],
          kp: "时态与语态",
        },
        {
          id: "E-ten-7",
          name: "时态综合辨析",
          level: "冲刺",
          minutes: 8,
          define: "根据时间状语与语境选时态。",
          why: "语法单选 20 分主力。",
          core: [
            { k: "完成 vs 过去", v: "for/since vs yesterday" },
            { k: "进行 vs 一般", v: "now vs every day" },
          ],
          steps: ["圈时间状语", "判断是否延续", "选结构"],
          example: {
            stem: "I ____ my keys. I can't find them.",
            analysis: "have lost（对现在影响）。",
          },
          mistakes: ["只看中文不管时态标志"],
          kp: "时态与语态",
        },
        {
          id: "E-ten-8",
          name: "主动表被动",
          level: "冲刺",
          minutes: 6,
          define: "有些动词主动形式可表被动（read well 等）。",
          why: "易混陷阱题。",
          core: [{ k: "常见", v: "want, need, be worth + doing" }],
          steps: ["看主语是否承受动作", "是否已有固定主动表被动"],
          example: {
            stem: "The book is worth ____.",
            analysis: "reading（不用 being read）。",
          },
          mistakes: ["全部改成被动"],
          kp: "时态与语态",
        },
      ],
    },
    {
      chapter: "非谓语动词",
      points: [
        {
          id: "E-non-1",
          name: "不定式 to do",
          level: "基础",
          minutes: 6,
          define: "表目的、将来或作主宾补。",
          why: "单选必考。",
          core: [
            { k: "常见动词", v: "want/decide/hope + to do" },
            { k: "句型", v: "It is adj. to do" },
          ],
          steps: ["看前接词", "判断是否表将来/目的"],
          example: {
            stem: "I want ____ (go).",
            analysis: "to go。",
          },
          mistakes: ["want doing"],
          kp: "非谓语动词",
        },
        {
          id: "E-non-2",
          name: "动名词 doing",
          level: "基础",
          minutes: 6,
          define: "作主语、宾语，或介词后。",
          why: "enjoy/finish/介词+doing。",
          core: [{ k: "口诀", v: "介词后跟 doing" }],
          steps: ["看是否介词后", "look forward to 等 to 是介词"],
          example: {
            stem: "I look forward to ____ (hear) from you.",
            analysis: "hearing。",
          },
          mistakes: ["to 一律当不定式"],
          kp: "非谓语动词",
        },
        {
          id: "E-non-3",
          name: "现在分词与过去分词",
          level: "强化",
          minutes: 7,
          define: "doing 主动/进行；done 被动/完成。",
          why: "定语、状语题。",
          core: [{ k: "判断", v: "与逻辑主语是主动还是被动" }],
          steps: ["找逻辑主语", "判断主被动", "选 doing/done"],
          example: {
            stem: "The man ____ (stand) at the door is my teacher.",
            analysis: "standing（主动）。",
          },
          mistakes: ["主动被动混"],
          kp: "非谓语动词",
        },
      ],
    },
  ],

  电工电子技术基础: [
    {
      chapter: "电路分析",
      points: [
        {
          id: "EE-cir-1",
          name: "欧姆定律",
          level: "基础",
          minutes: 6,
          define: "U=IR，线性电阻两端电压与电流成正比。",
          why: "一切电路计算的起点。",
          core: [
            { k: "公式", v: "U=IR，I=frac{U}{R}" },
            { k: "单位", v: "V, A, Ω" },
          ],
          steps: ["画出电路标已知", "选用公式", "代入数字（带单位）"],
          example: {
            stem: "R=10Ω，I=0.5A，求 U。",
            analysis: "U=IR=5V。",
          },
          mistakes: ["单位漏写", "非线性也用欧姆"],
          kp: "电路基本概念",
        },
        {
          id: "EE-cir-2",
          name: "基尔霍夫定律",
          level: "强化",
          minutes: 8,
          define: "KCL：ΣI=0；KVL：ΣU=0。",
          why: "复杂电路计算必考。",
          core: [
            { k: "KCL", v: "节点流入=流出" },
            { k: "KVL", v: "回路升=降" },
          ],
          steps: ["标方向", "列方程", "解方程组"],
          example: {
            stem: "节点流入 2A、3A，流出 I=？",
            analysis: "I=5A。",
          },
          mistakes: ["方向符号错"],
          kp: "直流电路分析",
        },
        {
          id: "EE-cir-3",
          name: "串并联等效",
          level: "强化",
          minutes: 7,
          define: "串 R=R1+R2；并 frac{1}{R}=frac{1}{R1}+frac{1}{R2}。",
          why: "等效电阻与分压分流。",
          core: [{ k: "并联特例", v: "R=R1R2/(R1+R2)" }],
          steps: ["识别串/并", "算等效", "再用欧姆"],
          example: {
            stem: "4Ω 与 12Ω 并联？",
            analysis: "3Ω。",
          },
          mistakes: ["并联当加"],
          kp: "直流电路分析",
        },
      ],
    },
    {
      chapter: "运算放大器",
      points: [
        {
          id: "EE-op-1",
          name: "反相放大",
          level: "强化",
          minutes: 7,
          define: "uo=−frac{Rf}{R1}·ui。",
          why: "电工计算高频。",
          core: [{ k: "要点", v: "输出与输入反相，有负号" }],
          steps: ["认接法", "算 A", "算 uo"],
          example: {
            stem: "R1=10k，Rf=50k，ui=0.2V。",
            analysis: "uo=−1V。",
          },
          mistakes: ["漏负号"],
          kp: "运算放大器",
        },
      ],
    },
  ],

  C语言程序设计: [
    {
      chapter: "指针",
      points: [
        {
          id: "C-ptr-1",
          name: "指针与地址",
          level: "基础",
          minutes: 7,
          define: "指针保存地址；*p 取该地址的值。",
          why: "C 语言难点、必考。",
          core: [
            { k: "&a", v: "取 a 的地址" },
            { k: "*p", v: "取 p 指向的值" },
          ],
          steps: ["画出变量与地址", "跟踪 p 指向谁", "读 *p"],
          example: {
            stem: "int a=5; int *p=&a; *p=?",
            analysis: "5。p 指向 a，*p 就是 a 的值。",
          },
          mistakes: ["*p 与 p 混", "未初始化指针"],
          kp: "指针与数组",
        },
        {
          id: "C-ptr-2",
          name: "指针与数组",
          level: "强化",
          minutes: 8,
          define: "a[i] ≡ *(a+i)；p+1 下一元素。",
          why: "程序阅读题主力。",
          core: [{ k: "注意", v: "p+1 是加一个元素不是 1 字节" }],
          steps: ["写地址序列", "算 *(p+k)", "对照 a[k]"],
          example: {
            stem: "a[5]={2,4,6,8,10}; p=a; *(p+3)=?",
            analysis: "8。",
          },
          mistakes: ["当字节偏移"],
          kp: "指针与数组",
        },
      ],
    },
    {
      chapter: "循环与算法",
      points: [
        {
          id: "C-loop-1",
          name: "for 循环与累加",
          level: "基础",
          minutes: 7,
          define: "按次数重复；sum 累加、max 求极值。",
          why: "程序阅读/填空。",
          core: [{ k: "模板", v: "for(i=0;i<n;i++) sum+=a[i];" }],
          steps: ["定初值", "写条件", "模拟每轮"],
          example: {
            stem: "sum=0; i=1..5 累加？",
            analysis: "15。",
          },
          mistakes: ["边界多跑", "max 初值 0"],
          kp: "循环与算法",
        },
      ],
    },
  ],

  计算机网络基础: [
    {
      chapter: "网络层",
      points: [
        {
          id: "N-ip-1",
          name: "IP 与子网划分",
          level: "强化",
          minutes: 10,
          define: "网络地址=IP∧掩码；可用主机=2^主机位−2。",
          why: "计算题最爱考。",
          core: [
            { k: "/24", v: "块 256，可用 254" },
            { k: "/26", v: "块 64，可用 62" },
            { k: "/27", v: "块 32，可用 30" },
          ],
          steps: ["写掩码/前缀", "算块大小", "网络/广播/可用"],
          example: {
            stem: "192.168.1.77/26 的网络地址？",
            analysis: "块 64，落在 64–127，网络 192.168.1.64。",
          },
          mistakes: ["网络当成最小主机", "可用忘减 2"],
          kp: "IP与子网",
        },
        {
          id: "N-ip-2",
          name: "ARP / ICMP",
          level: "基础",
          minutes: 6,
          define: "ARP：IP→MAC；ICMP：ping 差错报告。",
          why: "概念填空。",
          core: [{ k: "区分", v: "ARP 二层，ICMP 网络层" }],
          steps: ["回忆功能", "匹配缩写"],
          example: {
            stem: "ping 使用的协议？",
            analysis: "ICMP。",
          },
          mistakes: ["ARP 解析域名"],
          kp: "IP与子网",
        },
      ],
    },
    {
      chapter: "运输层",
      points: [
        {
          id: "N-tcp-1",
          name: "TCP 三次握手",
          level: "强化",
          minutes: 7,
          define: "SYN → SYN+ACK → ACK。",
          why: "简答/选择。",
          core: [{ k: "对比", v: "挥手一般四次" }],
          steps: ["按序写三步报文"],
          example: {
            stem: "建立连接几步？",
            analysis: "3 步。",
          },
          mistakes: ["与挥手次数混"],
          kp: "传输层",
        },
      ],
    },
  ],
};
