/* 最后一波，突破3000词 */
window.WORDBOOK_EXTRA4 = window.WORDBOOK_EXTRA4 || [];

const fgWords = [
  // F开头
  {w:"face",p:"feɪs",m:"n.脸 v.面对"},
  {w:"fact",p:"fækt",m:"n.事实"},
  {w:"factory",p:"ˈfæktri",m:"n.工厂"},
  {w:"fail",p:"feɪl",m:"v.失败"},
  {w:"failure",p:"ˈfeɪljə",m:"n.失败"},
  {w:"fair",p:"feə",m:"adj.公平的 n.集市"},
  {w:"faith",p:"feɪθ",m:"n.信仰"},
  {w:"fall",p:"fɔːl",m:"v.落下 n.秋天"},
  {w:"false",p:"fɔːls",m:"adj.错误的"},
  {w:"fame",p:"feɪm",m:"n.名声"},
  {w:"family",p:"ˈfæməli",m:"n.家庭"},
  {w:"famous",p:"ˈfeɪməs",m:"adj.著名的"},
  {w:"fan",p:"fæn",m:"n.风扇，粉丝"},
  {w:"far",p:"fɑː",m:"adj.远的 adv.远"},
  {w:"farm",p:"fɑːm",m:"n.农场"},
  {w:"farmer",p:"ˈfɑːmə",m:"n.农民"},
  {w:"fast",p:"fɑːst",m:"adj.快的 adv.快"},
  {w:"fat",p:"fæt",m:"adj.胖的 n.脂肪"},
  {w:"father",p:"ˈfɑːðə",m:"n.父亲"},
  {w:"fault",p:"fɔːlt",m:"n.错误"},
  {w:"favor",p:"ˈfeɪvə",m:"n.好感 v.支持"},
  {w:"favorite",p:"ˈfeɪvərɪt",m:"adj.最喜欢的"},
  {w:"fear",p:"fɪə",m:"n.害怕 v.害怕"},
  {w:"feather",p:"ˈfeðə",m:"n.羽毛"},
  {w:"february",p:"ˈfebruəri",m:"n.二月"},
  {w:"feed",p:"fiːd",m:"v.喂"},
  {w:"feel",p:"fiːl",m:"v.感觉"},
  {w:"feeling",p:"ˈfiːlɪŋ",m:"n.感觉"},
  {w:"fellow",p:"ˈfeləʊ",m:"n.家伙"},
  {w:"female",p:"ˈfiːmeɪl",m:"adj.女性的"},
  {w:"fence",p:"fens",m:"n.栅栏"},
  {w:"festival",p:"ˈfestɪvl",m:"n.节日"},
  {w:"fever",p:"ˈfiːvə",m:"n.发烧"},
  {w:"few",p:"fjuː",m:"adj.少数的"},
  {w:"field",p:"fiːld",m:"n.田野"},
  {w:"fifteen",p:"ˌfɪfˈtiːn",m:"num.十五"},
  {w:"fifth",p:"fɪfθ",m:"num.第五"},
  {w:"fifty",p:"ˈfɪfti",m:"num.五十"},
  {w:"fight",p:"faɪt",m:"v./n.打架"},
  {w:"fill",p:"fɪl",m:"v.填满"},
  {w:"film",p:"fɪlm",m:"n.电影"},
  {w:"final",p:"ˈfaɪnl",m:"adj.最后的"},
  {w:"finally",p:"ˈfaɪnəli",m:"adv.最后"},
  {w:"find",p:"faɪnd",m:"v.找到"},
  {w:"fine",p:"faɪn",m:"adj.好的 n.罚款"},
  {w:"finger",p:"ˈfɪŋɡə",m:"n.手指"},
  {w:"finish",p:"ˈfɪnɪʃ",m:"v.完成"},
  {w:"fire",p:"ˈfaɪə",m:"n.火 v.开火"},
  {w:"fireman",p:"ˈfaɪəmən",m:"n.消防员"},
  {w:"firm",p:"fɜːm",m:"n.公司 adj.坚定的"},
  {w:"first",p:"fɜːst",m:"num.第一 adv.首先"},
  {w:"fish",p:"fɪʃ",m:"n.鱼 v.钓鱼"},
  {w:"fit",p:"fɪt",m:"adj.合适的 v.适合"},
  {w:"five",p:"faɪv",m:"num.五"},
  {w:"fix",p:"fɪks",m:"v.修理"},
  {w:"flag",p:"flæɡ",m:"n.旗帜"},
  {w:"flash",p:"flæʃ",m:"n.闪光"},
  {w:"flat",p:"flæt",m:"adj.平的 n.公寓"},
  {w:"flight",p:"flaɪt",m:"n.航班"},
  {w:"float",p:"fləʊt",m:"v.漂浮"},
  {w:"floor",p:"flɔː",m:"n.地板"},
  {w:"flower",p:"ˈflaʊə",m:"n.花"},
  {w:"fly",p:"flaɪ",m:"v.飞 n.苍蝇"},
  {w:"fog",p:"fɒɡ",m:"n.雾"},
  {w:"fold",p:"fəʊld",m:"v.折叠"},
  {w:"follow",p:"ˈfɒləʊ",m:"v.跟随"},
  {w:"food",p:"fuːd",m:"n.食物"},
  {w:"fool",p:"fuːl",m:"n.傻子 v.愚弄"},
  {w:"foot",p:"fʊt",m:"n.脚"},
  {w:"football",p:"ˈfʊtbɔːl",m:"n.足球"},
  {w:"for",p:"fɔː",m:"prep.为了 conj.因为"},
  {w:"force",p:"fɔːs",m:"n.力量 v.强迫"},
  {w:"foreign",p:"ˈfɒrən",m:"adj.外国的"},
  {w:"forest",p:"ˈfɒrɪst",m:"n.森林"},
  {w:"forever",p:"fərˈevə",m:"adv.永远"},
  {w:"forget",p:"fəˈɡet",m:"v.忘记"},
  {w:"forgive",p:"fəˈɡɪv",m:"v.原谅"},
  {w:"fork",p:"fɔːk",m:"n.叉子"},
  {w:"form",p:"fɔːm",m:"n.形式 v.形成"},
  {w:"forty",p:"ˈfɔːti",m:"num.四十"},
  {w:"forward",p:"ˈfɔːwəd",m:"adv.向前"},
  {w:"four",p:"fɔː",m:"num.四"},
  {w:"fourteen",p:"ˌfɔːˈtiːn",m:"num.十四"},
  {w:"fox",p:"fɒks",m:"n.狐狸"},
  {w:"france",p:"frɑːns",m:"n.法国"},
  {w:"free",p:"friː",m:"adj.自由的，免费的"},
  {w:"freedom",p:"ˈfriːdəm",m:"n.自由"},
  {w:"freeze",p:"friːz",m:"v.结冰"},
  {w:"fresh",p:"freʃ",m:"adj.新鲜的"},
  {w:"friday",p:"ˈfraɪdeɪ",m:"n.星期五"},
  {w:"fridge",p:"frɪdʒ",m:"n.冰箱"},
  {w:"friend",p:"frend",m:"n.朋友"},
  {w:"friendly",p:"ˈfrendli",m:"adj.友好的"},
  {w:"friendship",p:"ˈfrendʃɪp",m:"n.友谊"},
  {w:"from",p:"frɒm",m:"prep.从"},
  {w:"front",p:"frʌnt",m:"n.前面 adj.前面的"},
  {w:"fruit",p:"fruːt",m:"n.水果"},
  {w:"full",p:"fʊl",m:"adj.满的"},
  {w:"fun",p:"fʌn",m:"n.乐趣 adj.有趣的"},
  {w:"funny",p:"ˈfʌni",m:"adj.有趣的"},
  {w:"future",p:"ˈfjuːtʃə",m:"n.未来"},

  // G开头
  {w:"gain",p:"ɡeɪn",m:"v.获得"},
  {w:"game",p:"ɡeɪm",m:"n.游戏"},
  {w:"garden",p:"ˈɡɑːdn",m:"n.花园"},
  {w:"gas",p:"ɡæs",m:"n.气体，汽油"},
  {w:"gate",p:"ɡeɪt",m:"n.大门"},
  {w:"gather",p:"ˈɡæðə",m:"v.聚集"},
  {w:"general",p:"ˈdʒenrəl",m:"adj.一般的 n.将军"},
  {w:"gentleman",p:"ˈdʒentlmən",m:"n.绅士"},
  {w:"geography",p:"dʒiˈɒɡrəfi",m:"n.地理"},
  {w:"get",p:"ɡet",m:"v.得到"},
  {w:"ghost",p:"ɡəʊst",m:"n.鬼"},
  {w:"girl",p:"ɡɜːl",m:"n.女孩"},
  {w:"give",p:"ɡɪv",m:"v.给"},
  {w:"glad",p:"ɡlæd",m:"adj.高兴的"},
  {w:"glass",p:"ɡlɑːs",m:"n.玻璃"},
  {w:"glasses",p:"ˈɡlɑːsɪz",m:"n.眼镜"},
  {w:"go",p:"ɡəʊ",m:"v.去"},
  {w:"goal",p:"ɡəʊl",m:"n.目标"},
  {w:"goat",p:"ɡəʊt",m:"n.山羊"},
  {w:"god",p:"ɡɒd",m:"n.神"},
  {w:"gold",p:"ɡəʊld",m:"n.黄金 adj.金的"},
  {w:"good",p:"ɡʊd",m:"adj.好的"},
  {w:"goodbye",p:"ˌɡʊdˈbaɪ",m:"int.再见"},
  {w:"goose",p:"ɡuːs",m:"n.鹅"},
  {w:"government",p:"ˈɡʌvənmənt",m:"n.政府"},
  {w:"grade",p:"ɡreɪd",m:"n.年级，分数"},
  {w:"gradually",p:"ˈɡrædʒuəli",m:"adv.逐渐地"},
  {w:"graduate",p:"ˈɡrædʒueɪt",m:"v.毕业"},
  {w:"grain",p:"ɡreɪn",m:"n.谷物"},
  {w:"grandfather",p:"ˈɡrænfɑːðə",m:"n.祖父"},
  {w:"grandmother",p:"ˈɡrænmʌðə",m:"n.祖母"},
  {w:"grass",p:"ɡrɑːs",m:"n.草"},
  {w:"grateful",p:"ˈɡreɪtfl",m:"adj.感激的"},
  {w:"great",p:"ɡreɪt",m:"adj.伟大的"},
  {w:"green",p:"ɡriːn",m:"adj.绿色的 n.绿色"},
  {w:"greet",p:"ɡriːt",m:"v.问候"},
  {w:"ground",p:"ɡraʊnd",m:"n.地面"},
  {w:"group",p:"ɡruːp",m:"n.组"},
  {w:"grow",p:"ɡrəʊ",m:"v.生长"},
  {w:"guard",p:"ɡɑːd",m:"v.守卫 n.警卫"},
  {w:"guess",p:"ɡes",m:"v.猜测"},
  {w:"guest",p:"ɡest",m:"n.客人"},
  {w:"guide",p:"ɡaɪd",m:"v.引导 n.向导"},
  {w:"guitar",p:"ɡɪˈtɑː",m:"n.吉他"},
  {w:"gun",p:"ɡʌn",m:"n.枪"}
];

// 合并
if (typeof window.WORDBOOK_DATA !== 'undefined') {
  window.WORDBOOK_DATA = window.WORDBOOK_DATA.concat(fgWords);
}

console.log("F-G开头补充" + fgWords.length + "个！总计突破3000！");
