/* 继续补充高频词汇到3000 */
window.WORDBOOK_EXTRA2 = window.WORDBOOK_EXTRA2 || [];

const moreWords = [
  // C开头
  {w:"cabbage",p:"ˈkæbɪdʒ",m:"n.卷心菜"},
  {w:"cafe",p:"ˈkæfeɪ",m:"n.咖啡馆"},
  {w:"cage",p:"keɪdʒ",m:"n.笼子"},
  {w:"cake",p:"keɪk",m:"n.蛋糕"},
  {w:"call",p:"kɔːl",m:"v.呼叫 n.电话"},
  {w:"calm",p:"kɑːm",m:"adj.平静的 v.使平静"},
  {w:"camera",p:"ˈkæmərə",m:"n.相机"},
  {w:"camp",p:"kæmp",m:"n.营地 v.露营"},
  {w:"can",p:"kæn",m:"v.能 n.罐头"},
  {w:"canal",p:"kəˈnæl",m:"n.运河"},
  {w:"cancel",p:"ˈkænsl",m:"v.取消"},
  {w:"cancer",p:"ˈkænsə",m:"n.癌症"},
  {w:"candidate",p:"ˈkændɪdət",m:"n.候选人"},
  {w:"candle",p:"ˈkændl",m:"n.蜡烛"},
  {w:"candy",p:"ˈkændi",m:"n.糖果"},
  {w:"canteen",p:"kænˈtiːn",m:"n.食堂"},
  {w:"cap",p:"kæp",m:"n.帽子"},
  {w:"capital",p:"ˈkæpɪtl",m:"n.首都，资本"},
  {w:"captain",p:"ˈkæptɪn",m:"n.队长，船长"},
  {w:"capture",p:"ˈkæptʃə",m:"v.捕获，拍摄"},
  {w:"car",p:"kɑː",m:"n.汽车"},
  {w:"card",p:"kɑːd",m:"n.卡片"},
  {w:"care",p:"keə",m:"n.关心 v.在意"},
  {w:"careful",p:"ˈkeəfl",m:"adj.小心的"},
  {w:"careless",p:"ˈkeələs",m:"adj.粗心的"},
  {w:"carpet",p:"ˈkɑːpɪt",m:"n.地毯"},
  {w:"carry",p:"ˈkæri",m:"v.携带，搬运"},
  {w:"cartoon",p:"kɑːˈtuːn",m:"n.卡通"},
  {w:"case",p:"keɪs",m:"n.情况，案例"},
  {w:"cash",p:"kæʃ",m:"n.现金"},
  {w:"castle",p:"ˈkɑːsl",m:"n.城堡"},
  {w:"cat",p:"kæt",m:"n.猫"},
  {w:"catch",p:"kætʃ",m:"v.抓住，赶上"},
  {w:"cattle",p:"ˈkætl",m:"n.牛"},
  {w:"cause",p:"kɔːz",m:"n.原因 v.导致"},
  {w:"cave",p:"keɪv",m:"n.洞穴"},
  {w:"ceiling",p:"ˈsiːlɪŋ",m:"n.天花板"},
  {w:"celebrate",p:"ˈselɪbreɪt",m:"v.庆祝"},
  {w:"celebration",p:"ˌselɪˈbreɪʃn",m:"n.庆祝"},
  {w:"cell",p:"sel",m:"n.细胞，手机"},
  {w:"cent",p:"sent",m:"n.分，美分"},
  {w:"central",p:"ˈsentrəl",m:"adj.中心的"},
  {w:"centre",p:"ˈsentə",m:"n.中心"},
  {w:"century",p:"ˈsentʃəri",m:"n.世纪"},
  {w:"certain",p:"ˈsɜːtn",m:"adj.确定的，某个"},
  {w:"certainly",p:"ˈsɜːtnli",m:"adv.当然"},
  {w:"chain",p:"tʃeɪn",m:"n.链条"},
  {w:"chair",p:"tʃeə",m:"n.椅子"},
  {w:"chairman",p:"ˈtʃeəmən",m:"n.主席"},
  {w:"chalk",p:"tʃɔːk",m:"n.粉笔"},
  {w:"chance",p:"tʃɑːns",m:"n.机会"},
  {w:"change",p:"tʃeɪndʒ",m:"v.改变 n.零钱"},
  {w:"channel",p:"ˈtʃænl",m:"n.频道，海峡"},
  {w:"chapter",p:"ˈtʃæptə",m:"n.章节"},
  {w:"character",p:"ˈkærəktə",m:"n.性格，角色"},
  {w:"charge",p:"tʃɑːdʒ",m:"v.收费，充电 n.费用"},
  {w:"chart",p:"tʃɑːt",m:"n.图表"},
  {w:"chase",p:"tʃeɪs",m:"v.追逐"},
  {w:"cheap",p:"tʃiːp",m:"adj.便宜的"},
  {w:"cheat",p:"tʃiːt",m:"v.作弊，欺骗"},
  {w:"check",p:"tʃek",m:"v.检查 n.支票"},
  {w:"cheer",p:"tʃɪə",m:"v.欢呼"},
  {w:"cheese",p:"tʃiːz",m:"n.奶酪"},
  {w:"chemistry",p:"ˈkemɪstri",m:"n.化学"},
  {w:"chess",p:"tʃes",m:"n.国际象棋"},
  {w:"chest",p:"tʃest",m:"n.胸部"},
  {w:"chicken",p:"ˈtʃɪkɪn",m:"n.鸡，鸡肉"},
  {w:"chief",p:"tʃiːf",m:"adj.主要的 n.首领"},
  {w:"child",p:"tʃaɪld",m:"n.孩子"},
  {w:"childhood",p:"ˈtʃaɪldhʊd",m:"n.童年"},
  {w:"chocolate",p:"ˈtʃɒklət",m:"n.巧克力"},
  {w:"choice",p:"tʃɔɪs",m:"n.选择"},
  {w:"choose",p:"tʃuːz",m:"v.选择"},
  {w:"church",p:"tʃɜːtʃ",m:"n.教堂"},
  {w:"cigarette",p:"ˌsɪɡəˈret",m:"n.香烟"},
  {w:"cinema",p:"ˈsɪnəmə",m:"n.电影院"},
  {w:"circle",p:"ˈsɜːkl",m:"n.圆圈 v.环绕"},
  {w:"citizen",p:"ˈsɪtɪzn",m:"n.公民"},
  {w:"city",p:"ˈsɪti",m:"n.城市"},
  {w:"civil",p:"ˈsɪvl",m:"adj.公民的，民事的"},
  {w:"claim",p:"kleɪm",m:"v.声称，索赔"},
  {w:"clap",p:"klæp",m:"v.鼓掌"},
  {w:"class",p:"klɑːs",m:"n.班级，阶级"},
  {w:"classmate",p:"ˈklɑːsmeɪt",m:"n.同学"},
  {w:"classroom",p:"ˈklɑːsruːm",m:"n.教室"},
  {w:"clean",p:"kliːn",m:"adj.干净的 v.打扫"},
  {w:"clear",p:"klɪə",m:"adj.清楚的 v.清理"},
  {w:"clever",p:"ˈklevə",m:"adj.聪明的"},
  {w:"climb",p:"klaɪm",m:"v.爬"},
  {w:"clinic",p:"ˈklɪnɪk",m:"n.诊所"},
  {w:"clock",p:"klɒk",m:"n.时钟"},
  {w:"close",p:"kləʊz",m:"v.关闭 adj.近的"},
  {w:"cloth",p:"klɒθ",m:"n.布"},
  {w:"clothes",p:"kləʊðz",m:"n.衣服"},
  {w:"cloud",p:"klaʊd",m:"n.云"},
  {w:"club",p:"klʌb",m:"n.俱乐部"},
  {w:"coach",p:"kəʊtʃ",m:"n.教练，长途汽车"},
  {w:"coal",p:"kəʊl",m:"n.煤"},
  {w:"coast",p:"kəʊst",m:"n.海岸"},
  {w:"coat",p:"kəʊt",m:"n.外套"},
  {w:"cock",p:"kɒk",m:"n.公鸡"},
  {w:"coffee",p:"ˈkɒfi",m:"n.咖啡"},
  {w:"coin",p:"kɔɪn",m:"n.硬币"},
  {w:"cold",p:"kəʊld",m:"adj.冷的 n.感冒"},
  {w:"collar",p:"ˈkɒlə",m:"n.衣领"},
  {w:"collect",p:"kəˈlekt",m:"v.收集"},
  {w:"college",p:"ˈkɒlɪdʒ",m:"n.大学，学院"},
  {w:"colour",p:"ˈkʌlə",m:"n.颜色"},
  {w:"comb",p:"kəʊm",m:"n.梳子 v.梳理"},
  {w:"combine",p:"kəmˈbaɪn",m:"v.结合"},
  {w:"come",p:"kʌm",m:"v.来"},
  {w:"comfort",p:"ˈkʌmfət",m:"n.舒适 v.安慰"},
  {w:"comfortable",p:"ˈkʌmftəbl",m:"adj.舒适的"},
  {w:"command",p:"kəˈmɑːnd",m:"v./n.命令"},
  {w:"comment",p:"ˈkɒment",m:"n./v.评论"},
  {w:"common",p:"ˈkɒmən",m:"adj.普通的，共同的"},
  {w:"communicate",p:"kəˈmjuːnɪkeɪt",m:"v.交流"},
  {w:"communication",p:"kəˌmjuːnɪˈkeɪʃn",m:"n.交流"},
  {w:"communism",p:"ˈkɒmjunɪzəm",m:"n.共产主义"},
  {w:"companion",p:"kəmˈpæniən",m:"n.同伴"},
  {w:"company",p:"ˈkʌmpəni",m:"n.公司，陪伴"},
  {w:"compare",p:"kəmˈpeə",m:"v.比较"},
  {w:"compete",p:"kəmˈpiːt",m:"v.竞争"},
  {w:"competition",p:"ˌkɒmpəˈtɪʃn",m:"n.比赛"},
  {w:"complain",p:"kəmˈpleɪn",m:"v.抱怨"},
  {w:"complete",p:"kəmˈpliːt",m:"adj.完整的 v.完成"},
  {w:"complex",p:"ˈkɒmpleks",m:"adj.复杂的"},
  {w:"composition",p:"ˌkɒmpəˈzɪʃn",m:"n.作文，构成"},
  {w:"composition",p:"ˌkɒmpəˈzɪʃn",m:"n.作文"},
  {w:"computer",p:"kəmˈpjuːtə",m:"n.电脑"},
  {w:"concentrate",p:"ˈkɒnsntreɪt",m:"v.集中"},
  {w:"concept",p:"ˈkɒnsept",m:"n.概念"},
  {w:"concern",p:"kənˈsɜːn",m:"n.关心 v.涉及"},
  {w:"concert",p:"ˈkɒnsət",m:"n.音乐会"},
  {w:"condition",p:"kənˈdɪʃn",m:"n.条件，状况"},
  {w:"conduct",p:"kənˈdʌkt",m:"v.引导 n.行为"},
  {w:"conductor",p:"kənˈdʌktə",m:"n.售票员，指挥"},
  {w:"congratulation",p:"kənˌɡrætʃuˈleɪʃn",m:"n.祝贺"},
  {w:"connect",p:"kəˈnekt",m:"v.连接"},
  {w:"connection",p:"kəˈnekʃn",m:"n.连接"},
  {w:"conscience",p:"ˈkɒnʃəns",m:"n.良心"},
  {w:"consider",p:"kənˈsɪdə",m:"v.考虑"},
  {w:"consist",p:"kənˈsɪst",m:"v.组成，在于"},
  {w:"constant",p:"ˈkɒnstənt",m:"adj.不断的"},
  {w:"construction",p:"kənˈstrʌkʃn",m:"n.建设"},
  {w:"contribution",p:"ˌkɒntrɪˈbjuːʃn",m:"n.贡献"},
  {w:"control",p:"kənˈtrəʊl",m:"v./n.控制"},
  {w:"convenient",p:"kənˈviːniənt",m:"adj.方便的"},
  {w:"conversation",p:"ˌkɒnvəˈseɪʃn",m:"n.对话"},
  {w:"cook",p:"kʊk",m:"v.做饭 n.厨师"},
  {w:"cookie",p:"ˈkʊki",m:"n.饼干"},
  {w:"cool",p:"kuːl",m:"adj.凉的，酷的"},
  {w:"copy",p:"ˈkɒpi",m:"v.复制 n.副本"},
  {w:"corn",p:"kɔːn",m:"n.玉米"},
  {w:"corner",p:"ˈkɔːnə",m:"n.角落"},
  {w:"correct",p:"kəˈrekt",m:"adj.正确的 v.纠正"},
  {w:"cost",p:"kɒst",m:"v.花费 n.成本"},
  {w:"cottage",p:"ˈkɒtɪdʒ",m:"n.小屋"},
  {w:"cotton",p:"ˈkɒtn",m:"n.棉花"},
  {w:"cough",p:"kɒf",m:"v./n.咳嗽"},
  {w:"could",p:"kʊd",m:"v.能（can过去式）"},
  {w:"count",p:"kaʊnt",m:"v.数，计算"},
  {w:"counter",p:"ˈkaʊntə",m:"n.柜台"},
  {w:"country",p:"ˈkʌntri",m:"n.国家，乡村"},
  {w:"countryside",p:"ˈkʌntrisaɪd",m:"n.乡村"},
  {w:"county",p:"ˈkaʊnti",m:"n.县"},
  {w:"couple",p:"ˈkʌpl",m:"n.一对，夫妇"},
  {w:"courage",p:"ˈkʌrɪdʒ",m:"n.勇气"},
  {w:"course",p:"kɔːs",m:"n.课程，过程"},
  {w:"court",p:"kɔːt",m:"n.法庭，球场"},
  {w:"cousin",p:"ˈkʌzn",m:"n.堂/表兄弟姐妹"},
  {w:"cover",p:"ˈkʌvə",m:"v.覆盖 n.封面"},
  {w:"cow",p:"kaʊ",m:"n.奶牛"},
  {w:"crash",p:"kræʃ",m:"v.碰撞，崩溃"},
  {w:"crazy",p:"ˈkreɪzi",m:"adj.疯狂的"},
  {w:"cream",p:"kriːm",m:"n.奶油"},
  {w:"create",p:"kriˈeɪt",m:"v.创造"},
  {w:"credit",p:"ˈkredɪt",m:"n.信用，学分"},
  {w:"crew",p:"kruː",m:"n.全体船员"},
  {w:"crime",p:"kraɪm",m:"n.犯罪"},
  {w:"criminal",p:"ˈkrɪmɪnl",m:"n.罪犯"},
  {w:"crop",p:"krɒp",m:"n.庄稼"},
  {w:"cross",p:"krɒs",m:"v.穿过 n.十字"},
  {w:"crowd",p:"kraʊd",m:"n.人群"},
  {w:"cruel",p:"ˈkruːəl",m:"adj.残忍的"},
  {w:"cry",p:"kraɪ",m:"v.哭 n.哭声"},
  {w:"culture",p:"ˈkʌltʃə",m:"n.文化"},
  {w:"cup",p:"kʌp",m:"n.杯子"},
  {w:"cupboard",p:"ˈkʌbəd",m:"n.橱柜"},
  {w:"cure",p:"kjʊə",m:"v.治愈 n.治疗"},
  {w:"curious",p:"ˈkjʊəriəs",m:"adj.好奇的"},
  {w:"current",p:"ˈkʌrənt",m:"adj.当前的 n.电流"},
  {w:"curtain",p:"ˈkɜːtn",m:"n.窗帘"},
  {w:"curve",p:"kɜːv",m:"n.曲线"},
  {w:"custom",p:"ˈkʌstəm",m:"n.习惯，风俗"},
  {w:"customer",p:"ˈkʌstəmə",m:"n.顾客"},
  {w:"cut",p:"kʌt",m:"v.切，割"},
  {w:"cycle",p:"ˈsaɪkl",m:"n.循环 v.骑自行车"}
];

// 合并到单词本
if (typeof window.WORDBOOK_DATA !== 'undefined') {
  window.WORDBOOK_DATA = window.WORDBOOK_DATA.concat(moreWords);
}

console.log("继续补充词汇" + moreWords.length + "个！");
