/* 补充D-Z高频词汇，突破3000 */
window.WORDBOOK_EXTRA3 = window.WORDBOOK_EXTRA3 || [];

const dzWords = [
  // D开头
  {w:"daily",p:"ˈdeɪli",m:"adj.每日的 adv.每天"},
  {w:"dance",p:"dɑːns",m:"v.跳舞 n.舞蹈"},
  {w:"danger",p:"ˈdeɪndʒə",m:"n.危险"},
  {w:"dangerous",p:"ˈdeɪndʒərəs",m:"adj.危险的"},
  {w:"dare",p:"deə",m:"v.敢"},
  {w:"dark",p:"dɑːk",m:"adj.黑暗的 n.黑暗"},
  {w:"data",p:"ˈdeɪtə",m:"n.数据"},
  {w:"date",p:"deɪt",m:"n.日期 v.约会"},
  {w:"daughter",p:"ˈdɔːtə",m:"n.女儿"},
  {w:"day",p:"deɪ",m:"n.天，白天"},
  {w:"dead",p:"ded",m:"adj.死的"},
  {w:"deaf",p:"def",m:"adj.聋的"},
  {w:"deal",p:"diːl",m:"v.处理 n.交易"},
  {w:"dear",p:"dɪə",m:"adj.亲爱的"},
  {w:"death",p:"deθ",m:"n.死亡"},
  {w:"december",p:"dɪˈsembə",m:"n.十二月"},
  {w:"decide",p:"dɪˈsaɪd",m:"v.决定"},
  {w:"decision",p:"dɪˈsɪʒn",m:"n.决定"},
  {w:"declare",p:"dɪˈkleə",m:"v.宣布"},
  {w:"decorate",p:"ˈdekəreɪt",m:"v.装饰"},
  {w:"deed",p:"diːd",m:"n.行为"},
  {w:"deep",p:"diːp",m:"adj.深的"},
  {w:"deer",p:"dɪə",m:"n.鹿"},
  {w:"defeat",p:"dɪˈfiːt",m:"v.击败"},
  {w:"defend",p:"dɪˈfend",m:"v.保卫"},
  {w:"degree",p:"dɪˈɡriː",m:"n.度，学位"},
  {w:"delay",p:"dɪˈleɪ",m:"v./n.推迟"},
  {w:"delicious",p:"dɪˈlɪʃəs",m:"adj.美味的"},
  {w:"delight",p:"dɪˈlaɪt",m:"n.高兴 v.使高兴"},
  {w:"deliver",p:"dɪˈlɪvə",m:"v.递送"},
  {w:"demand",p:"dɪˈmɑːnd",m:"v./n.要求"},
  {w:"department",p:"dɪˈpɑːtmənt",m:"n.部门"},
  {w:"depend",p:"dɪˈpend",m:"v.依靠"},
  {w:"dependent",p:"dɪˈpendənt",m:"adj.依赖的"},
  {w:"describe",p:"dɪˈskraɪb",m:"v.描述"},
  {w:"description",p:"dɪˈskrɪpʃn",m:"n.描述"},
  {w:"desert",p:"ˈdezət",m:"n.沙漠"},
  {w:"design",p:"dɪˈzaɪn",m:"v./n.设计"},
  {w:"desire",p:"dɪˈzaɪə",m:"v./n.渴望"},
  {w:"desk",p:"desk",m:"n.书桌"},
  {w:"destroy",p:"dɪˈstrɔɪ",m:"v.破坏"},
  {w:"detail",p:"ˈdiːteɪl",m:"n.细节"},
  {w:"develop",p:"dɪˈveləp",m:"v.发展"},
  {w:"development",p:"dɪˈveləpmənt",m:"n.发展"},
  {w:"devote",p:"dɪˈvəʊt",m:"v.致力于"},
  {w:"diagram",p:"ˈdaɪəɡræm",m:"n.图表"},
  {w:"dialogue",p:"ˈdaɪəlɒɡ",m:"n.对话"},
  {w:"diamond",p:"ˈdaɪəmənd",m:"n.钻石"},
  {w:"diary",p:"ˈdaɪəri",m:"n.日记"},
  {w:"dictionary",p:"ˈdɪkʃənri",m:"n.字典"},
  {w:"die",p:"daɪ",m:"v.死"},
  {w:"difference",p:"ˈdɪfrəns",m:"n.不同"},
  {w:"different",p:"ˈdɪfrənt",m:"adj.不同的"},
  {w:"difficult",p:"ˈdɪfɪkəlt",m:"adj.困难的"},
  {w:"difficulty",p:"ˈdɪfɪkəlti",m:"n.困难"},
  {w:"dig",p:"dɪɡ",m:"v.挖"},
  {w:"dinner",p:"ˈdɪnə",m:"n.晚餐"},
  {w:"direct",p:"dəˈrekt",m:"adj.直接的 v.指导"},
  {w:"direction",p:"dəˈrekʃn",m:"n.方向"},
  {w:"director",p:"dəˈrektə",m:"n.导演，主任"},
  {w:"dirt",p:"dɜːt",m:"n.灰尘"},
  {w:"dirty",p:"ˈdɜːti",m:"adj.脏的"},
  {w:"discover",p:"dɪˈskʌvə",m:"v.发现"},
  {w:"discovery",p:"dɪˈskʌvəri",m:"n.发现"},
  {w:"discussion",p:"dɪˈskʌʃn",m:"n.讨论"},
  {w:"disease",p:"dɪˈziːz",m:"n.疾病"},
  {w:"dish",p:"dɪʃ",m:"n.盘子"},
  {w:"dismiss",p:"dɪsˈmɪs",m:"v.解雇，解散"},
  {w:"distance",p:"ˈdɪstəns",m:"n.距离"},
  {w:"distant",p:"ˈdɪstənt",m:"adj.遥远的"},
  {w:"divide",p:"dɪˈvaɪd",m:"v.分，划分"},
  {w:"do",p:"duː",m:"v.做"},
  {w:"doctor",p:"ˈdɒktə",m:"n.医生，博士"},
  {w:"dog",p:"dɒɡ",m:"n.狗"},
  {w:"doll",p:"dɒl",m:"n.玩偶"},
  {w:"dollar",p:"ˈdɒlə",m:"n.美元"},
  {w:"door",p:"dɔː",m:"n.门"},
  {w:"double",p:"ˈdʌbl",m:"adj.双倍的"},
  {w:"doubt",p:"daʊt",m:"v./n.怀疑"},
  {w:"down",p:"daʊn",m:"adv.向下"},
  {w:"downtown",p:"ˌdaʊnˈtaʊn",m:"adv.在市中心"},
  {w:"dozen",p:"ˈdʌzn",m:"n.一打"},
  {w:"draw",p:"drɔː",m:"v.画，拉"},
  {w:"dream",p:"driːm",m:"n.梦 v.梦想"},
  {w:"dress",p:"dres",m:"n.连衣裙 v.穿衣服"},
  {w:"drink",p:"drɪŋk",m:"v.喝 n.饮料"},
  {w:"drive",p:"draɪv",m:"v.驾驶"},
  {w:"driver",p:"ˈdraɪvə",m:"n.司机"},
  {w:"drop",p:"drɒp",m:"v.落下 n.滴"},
  {w:"drown",p:"draʊn",m:"v.溺水"},
  {w:"drug",p:"drʌɡ",m:"n.药，毒品"},
  {w:"dry",p:"draɪ",m:"adj.干的"},
  {w:"duck",p:"dʌk",m:"n.鸭子"},
  {w:"dull",p:"dʌl",m:"adj.枯燥的"},
  {w:"during",p:"ˈdjʊərɪŋ",m:"prep.在...期间"},
  {w:"duty",p:"ˈdjuːti",m:"n.责任"},

  // E开头
  {w:"each",p:"iːtʃ",m:"adj.每个 pron.每个"},
  {w:"ear",p:"ɪə",m:"n.耳朵"},
  {w:"early",p:"ˈɜːli",m:"adj.早的 adv.早"},
  {w:"earn",p:"ɜːn",m:"v.挣得"},
  {w:"earth",p:"ɜːθ",m:"n.地球"},
  {w:"east",p:"iːst",m:"n.东方 adj.东方的"},
  {w:"easy",p:"ˈiːzi",m:"adj.容易的"},
  {w:"eat",p:"iːt",m:"v.吃"},
  {w:"edge",p:"edʒ",m:"n.边缘"},
  {w:"education",p:"ˌedʒuˈkeɪʃn",m:"n.教育"},
  {w:"effect",p:"ɪˈfekt",m:"n.效果"},
  {w:"effort",p:"ˈefət",m:"n.努力"},
  {w:"egg",p:"eɡ",m:"n.鸡蛋"},
  {w:"eight",p:"eɪt",m:"num.八"},
  {w:"eighteen",p:"ˌeɪˈtiːn",m:"num.十八"},
  {w:"eighty",p:"ˈeɪti",m:"num.八十"},
  {w:"either",p:"ˈaɪðə",m:"pron.两者之一 adv.也"},
  {w:"elder",p:"ˈeldə",m:"adj.年长的"},
  {w:"elect",p:"ɪˈlekt",m:"v.选举"},
  {w:"electric",p:"ɪˈlektrɪk",m:"adj.电的"},
  {w:"elephant",p:"ˈelɪfənt",m:"n.大象"},
  {w:"elevator",p:"ˈelɪveɪtə",m:"n.电梯"},
  {w:"else",p:"els",m:"adv.其他的"},
  {w:"employ",p:"ɪmˈplɔɪ",m:"v.雇佣"},
  {w:"empty",p:"ˈempti",m:"adj.空的"},
  {w:"end",p:"end",m:"n.结束 v.结束"},
  {w:"enemy",p:"ˈenəmi",m:"n.敌人"},
  {w:"energy",p:"ˈenədʒi",m:"n.能量"},
  {w:"engine",p:"ˈendʒɪn",m:"n.发动机"},
  {w:"engineer",p:"ˌendʒɪˈnɪə",m:"n.工程师"},
  {w:"english",p:"ˈɪŋɡlɪʃ",m:"n.英语"},
  {w:"enjoy",p:"ɪnˈdʒɔɪ",m:"v.享受"},
  {w:"enough",p:"ɪˈnʌf",m:"adj.足够的 adv.足够"},
  {w:"enter",p:"ˈentə",m:"v.进入"},
  {w:"entire",p:"ɪnˈtaɪə",m:"adj.整个的"},
  {w:"entrance",p:"ˈentrəns",m:"n.入口"},
  {w:"envelope",p:"ˈenvələʊp",m:"n.信封"},
  {w:"environment",p:"ɪnˈvaɪrənmənt",m:"n.环境"},
  {w:"especially",p:"ɪˈspeʃəli",m:"adv.特别地"},
  {w:"europe",p:"ˈjʊərəp",m:"n.欧洲"},
  {w:"even",p:"ˈiːvn",m:"adv.甚至 adj.平的"},
  {w:"evening",p:"ˈiːvnɪŋ",m:"n.晚上"},
  {w:"event",p:"ɪˈvent",m:"n.事件"},
  {w:"ever",p:"ˈevə",m:"adv.曾经"},
  {w:"every",p:"ˈevri",m:"adj.每个"},
  {w:"everybody",p:"ˈevribɒdi",m:"pron.每个人"},
  {w:"everyday",p:"ˈevrideɪ",m:"adj.日常的"},
  {w:"everyone",p:"ˈevriwʌn",m:"pron.每个人"},
  {w:"everything",p:"ˈevriθɪŋ",m:"pron.一切"},
  {w:"everywhere",p:"ˈevriweə",m:"adv.到处"},
  {w:"exact",p:"ɪɡˈzækt",m:"adj.精确的"},
  {w:"exam",p:"ɪɡˈzæm",m:"n.考试"},
  {w:"examination",p:"ɪɡˌzæmɪˈneɪʃn",m:"n.考试"},
  {w:"examine",p:"ɪɡˈzæmɪn",m:"v.检查"},
  {w:"example",p:"ɪɡˈzɑːmpl",m:"n.例子"},
  {w:"excellent",p:"ˈeksələnt",m:"adj.优秀的"},
  {w:"except",p:"ɪkˈsept",m:"prep.除了"},
  {w:"excite",p:"ɪkˈsaɪt",m:"v.使兴奋"},
  {w:"exciting",p:"ɪkˈsaɪtɪŋ",m:"adj.令人兴奋的"},
  {w:"excuse",p:"ɪkˈskjuːz",m:"v.原谅 n.借口"},
  {w:"exercise",p:"ˈeksəsaɪz",m:"n.练习 v.锻炼"},
  {w:"exhibition",p:"ˌeksɪˈbɪʃn",m:"n.展览"},
  {w:"exist",p:"ɪɡˈzɪst",m:"v.存在"},
  {w:"expect",p:"ɪkˈspekt",m:"v.期待"},
  {w:"expensive",p:"ɪkˈspensɪv",m:"adj.贵的"},
  {w:"experience",p:"ɪkˈspɪəriəns",m:"n.经验"},
  {w:"experiment",p:"ɪkˈsperɪmənt",m:"n.实验"},
  {w:"explain",p:"ɪkˈspleɪn",m:"v.解释"},
  {w:"explanation",p:"ˌekspləˈneɪʃn",m:"n.解释"},
  {w:"explode",p:"ɪkˈspləʊd",m:"v.爆炸"},
  {w:"express",p:"ɪkˈspres",m:"v.表达 n.快车"},
  {w:"extra",p:"ˈekstrə",m:"adj.额外的"},
  {w:"extraordinary",p:"ɪkˈstrɔːdnri",m:"adj.非凡的"},
  {w:"eye",p:"aɪ",m:"n.眼睛"}
];

// 合并
if (typeof window.WORDBOOK_DATA !== 'undefined') {
  window.WORDBOOK_DATA = window.WORDBOOK_DATA.concat(dzWords);
}

console.log("D-E开头补充" + dzWords.length + "个！");
